name: em01
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em01
  asset_path: assets/em/em01
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em01.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em01.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em01.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em01
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em01.symbol_addrs.txt
  symbol_name_format: em01_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em01.ovl
  undefined_funcs_auto_path: build/config/em/em01.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em01.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x100
  name: em01
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em01_before_18578_r4v2_80]
  - [0x88, cpp, r4v2_state_88]
  - [0xc0, asm, em01_before_18578_r4v2_c0]
  - [0xf40, cpp, r4v2_state_f40]
  - [0xfc8, asm, em01_before_18578_r4v2_fc8]
  - [0x1690, cpp, r4v2_state_1690]
  - [0x1718, asm, em01_before_18578_r4v2_1718]
  - [0x1e20, cpp, r4v2_state_1e20]
  - [0x1ea8, asm, em01_before_18578_r4v2_1ea8]
  - [0x2068, cpp, r4v2_state_2068]
  - [0x20e0, asm, em01_before_18578_r4v2_20e0]
  - [0x2700, cpp, r4v2_state_2700]
  - [0x2778, asm, em01_before_18578_r4v2_2778]
  - [0x3478, cpp, action_18578]
  - [0x3600, asm, em01_before_24870_r4_3600_r4v2_3600]
  - [0x7e68, cpp, r4v2_state_7e68]
  - [0x7ef0, asm, em01_before_24870_r4_3600_r4v2_7ef0]
  - [0x8658, cpp, r4v2_state_8658]
  - [0x86e0, asm, em01_before_24870_r4_3600_r4v2_86e0]
  - [0xa300, cpp, r4_state_a300]
  - [0xa318, cpp, r4v2_state_a318]
  - [0xa368, asm, em01_before_24870_r4_a318_r4v2_a368_r5_a368]
  - [0xb6e0, cpp, r5_state_b6e0]
  - [0xb77c, pad]
  - [0xb780, cpp, r5_state_b780]
  - [0xb81c, pad]
  - [0xb820, cpp, r5_state_b820]
  - [0xb8bc, pad]
  - [0xb8c0, cpp, r5_state_b8c0]
  - [0xb95c, pad]
  - [0xb960, asm, em01_before_24870_r4_a318_r4v2_a368_r5_b960]
  - [0xc2c8, cpp, r5_state_c2c8]
  - [0xc364, pad]
  - [0xc368, asm, em01_before_24870_r4_a318_r4v2_a368_r5_c368]
  - [0xde58, cpp, r3_callbacks_de58]
  - [0xde68, asm, em01_before_24870_r3_de68]
  - [0xf770, cpp, dispatch_24870]
  - [0xf7f4, asm, dispatch_24870_gap]
  - [0xf7f8, asm, em01_r4_f7f8]
  - [0xf890, cpp, r4_state_f890]
  - [0xf8c4, pad]
  - [0xf8c8, asm, em01_r4_f8c8]
  - [0x10768, cpp, r3_callbacks_10768]
  - [0x10770, asm, em01_r3_10770]
  - [0x14c28, cpp, r3_callbacks_14c28]
  - [0x14c30, asm, em01_r3_14c30]
  - [0x1893c, pad]
  - [0x18980, data, em01]
  - [0x2b000, bss, em01]
  type: code
  vram: 0x09d15140
- - 0x2b000
sha1: 00300ab39ce8650f11eb6b532940d8c4a99e8d83
