name: em07
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em07
  asset_path: assets/em/em07
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em07.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em07.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em07.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em07
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em07.symbol_addrs.txt
  symbol_name_format: em07_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em07.ovl
  undefined_funcs_auto_path: build/config/em/em07.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em07.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em07
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em07_before_lifecycle_a098_r4v2_80]
  - [0x4d48, cpp, r4v2_state_4d48]
  - [0x4dc8, asm, em07_before_lifecycle_a098_r4v2_4dc8_r6_4dc8]
  - [0x5730, cpp, r6_callback_5730]
  - [0x57d0, cpp, r3_callbacks_57d0]
  - [0x57d8, cpp, r4v2_state_57d8]
  - [0x5858, asm, em07_before_lifecycle_a098_r3_57d8_r4_57d8_r4v2_5858]
  - [0x7008, cpp, r4_state_7008]
  - [0x7070, asm, em07_before_lifecycle_a098_r3_57d8_r4_7070_r4v2_7070]
  - [0x74b8, cpp, r4v2_state_74b8]
  - [0x74d0, cpp, r4_state_74d0]
  - [0x74e4, pad]
  - [0x74e8, cpp, r4_state_74e8]
  - [0x7504, pad]
  - [0x7508, cpp, r4_state_7508]
  - [0x7524, pad]
  - [0x7528, cpp, r4_state_7528]
  - [0x7544, pad]
  - [0x7548, cpp, r4_state_7548]
  - [0x7564, pad]
  - [0x7568, cpp, r4_state_7568]
  - [0x7588, cpp, r4_state_7588]
  - [0x75a8, cpp, r4_state_75a8]
  - [0x75c8, asm, em07_before_lifecycle_a098_r3_57d8_r4_75c8]
  - [0x76c8, cpp, r3_callbacks_76c8]
  - [0x76d8, cpp, r3_lifecycle_76d8_dtor]
  - [0x7734, pad]
  - [0x7738, cpp, r3_callbacks_7738]
  - [0x7740, asm, em07_before_lifecycle_a098_r3_7740]
  - [0xa098, cpp, lifecycle_a098_ctor]
  - [0xa0cc, asm, lifecycle_a098_gap1]
  - [0xa0d0, cpp, lifecycle_a098_dtor]
  - [0xa12c, asm, lifecycle_a098_gap2]
  - [0xa130, asm, em07_tail]
  - [0xa3b8, cpp, r3_callbacks_a3b8]
  - [0xa3c0, asm, em07_tail_r3_a3c0_r8_a3c0]
  - [0xa660, cpp, r8_ptmf_a660]
  - [0xa6d0, cpp, r3_callbacks_a6d0]
  - [0xa710, asm, em07_tail_r3_a710]
  - [0xa718, cpp, r3_callbacks_a718]
  - [0xa720, pad]
  - [0xa780, data, em07]
  - [0x12e00, bss, em07]
  type: code
  vram: 0x09d15140
- - 0x12e00
sha1: aa1218ff1743b338c4ef79f3d1f5aaa7f89b309c
