name: em14
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em14
  asset_path: assets/em/em14
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em14.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em14.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em14.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em14
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em14.symbol_addrs.txt
  symbol_name_format: em14_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em14.ovl
  undefined_funcs_auto_path: build/config/em/em14.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em14.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em14
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, cpp, r3_callbacks_80]
  - [0x88, asm, em14_before_lifecycle_f468_r4v2_88]
  - [0x1048, cpp, r4v2_state_1048]
  - [0x1080, asm, em14_before_lifecycle_f468_r4v2_1080]
  - [0x5450, cpp, r3_callbacks_5450]
  - [0x5458, asm, em14_before_lifecycle_f468_r3_5458]
  - [0x6128, cpp, r3_callbacks_6128]
  - [0x6130, asm, em14_before_lifecycle_f468_r3_6130]
  - [0x63b0, cpp, r3_callbacks_63b0]
  - [0x63b8, asm, em14_before_lifecycle_f468_r3_63b8]
  - [0x6490, cpp, r3_callbacks_6490]
  - [0x6498, asm, em14_before_lifecycle_f468_r3_6498_r4v2_6498]
  - [0x66d8, cpp, r4v2_state_66d8]
  - [0x6758, asm, em14_before_lifecycle_f468_r3_6498_r4v2_6758]
  - [0x68d8, cpp, r3_callbacks_68d8]
  - [0x68e0, asm, em14_before_lifecycle_f468_r3_68e0_r4v2_68e0]
  - [0x6ba0, cpp, r4v2_state_6ba0]
  - [0x6c20, asm, em14_before_lifecycle_f468_r3_68e0_r4v2_6c20]
  - [0x6de0, cpp, r4v2_state_6de0]
  - [0x6e50, cpp, r3_callbacks_6e50]
  - [0x6e58, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_6e58_r7_6e58]
  - [0x7188, cpp, r7_callback_7188]
  - [0x7250, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_6e58_r7_7250]
  - [0x75f0, cpp, r7_callback_75f0]
  - [0x76b8, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_6e58_r7_76b8]
  - [0x8e88, cpp, r7_callback_8e88]
  - [0x8f38, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_6e58_r7_8f38]
  - [0x94a0, cpp, r7_callback_94a0]
  - [0x9550, cpp, r4v2_state_9550]
  - [0x95d0, cpp, r7_callback_95d0]
  - [0x9680, cpp, r4v2_state_9680]
  - [0x9700, cpp, r4v2_state_9700]
  - [0x9780, cpp, r5_state_9780]
  - [0x9814, pad]
  - [0x9818, cpp, r5_state_9818]
  - [0x98ac, pad]
  - [0x98b0, cpp, r5_state_98b0]
  - [0x9944, pad]
  - [0x9948, cpp, r5_state_9948]
  - [0x99dc, pad]
  - [0x99e0, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_9780_r5_99e0]
  - [0x9fa8, cpp, r5_state_9fa8]
  - [0xa03c, pad]
  - [0xa040, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_9780_r5_a040]
  - [0xa338, cpp, r5_state_a338]
  - [0xa3cc, pad]
  - [0xa3d0, asm, em14_before_lifecycle_f468_r3_6e58_r4_6e58_r4v2_9780_r5_a3d0]
  - [0xca80, cpp, r4_state_ca80]
  - [0xcae8, cpp, r4_state_cae8]
  - [0xcb1c, pad]
  - [0xcb20, asm, em14_before_lifecycle_f468_r3_6e58_r4_cb20]
  - [0xd008, cpp, r3_callbacks_d008]
  - [0xd010, asm, em14_before_lifecycle_f468_r3_d010]
  - [0xf468, cpp, lifecycle_f468_ctor]
  - [0xf49c, asm, lifecycle_f468_gap1]
  - [0xf4a0, cpp, lifecycle_f468_dtor]
  - [0xf4fc, asm, lifecycle_f468_gap2]
  - [0xf500, asm, em14_tail]
  - [0xf590, cpp, r3_callbacks_f590]
  - [0xf598, asm, em14_tail_r3_f598_r8_f598]
  - [0xf8e0, cpp, r8_ptmf_f8e0]
  - [0xf950, cpp, r3_callbacks_f950]
  - [0xf990, asm, em14_tail_r3_f990]
  - [0xf998, cpp, r3_callbacks_f998]
  - [0xf9a0, pad]
  - [0xfa00, data, em14]
  - [0x16700, bss, em14]
  type: code
  vram: 0x09d15140
- - 0x16700
sha1: d0970cff180ffb5a8401784d97df00051b3aa168
