name: em17
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em17
  asset_path: assets/em/em17
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em17.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em17.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em17.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em17
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em17.symbol_addrs.txt
  symbol_name_format: em17_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em17.ovl
  undefined_funcs_auto_path: build/config/em/em17.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em17.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em17
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em17_before_lifecycle_10f88_r4v2_80]
  - [0xa08, cpp, r4v2_state_a08]
  - [0xa40, asm, em17_before_lifecycle_10f88_r4v2_a40]
  - [0x4270, cpp, r3_callbacks_4270]
  - [0x4278, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_4278]
  - [0x5670, cpp, r4v2_state_5670]
  - [0x56f0, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_56f0]
  - [0x5c70, cpp, r4v2_state_5c70]
  - [0x5ce0, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_5ce0]
  - [0x66f8, cpp, r4v2_state_66f8]
  - [0x6778, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6778_r7_6778]
  - [0x69e0, cpp, r7_callback_69e0]
  - [0x6aa8, cpp, r7_callback_6aa8]
  - [0x6b70, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6778_r7_6b70]
  - [0x6db0, cpp, r4v2_state_6db0]
  - [0x6e30, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6e30_r5_6e30_r7_6e30]
  - [0x8608, cpp, r7_callback_8608]
  - [0x86b8, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6e30_r5_6e30_r7_86b8]
  - [0x9478, cpp, r5_state_9478]
  - [0x950c, pad]
  - [0x9510, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6e30_r5_9510]
  - [0xa010, cpp, r5_state_a010]
  - [0xa0a4, pad]
  - [0xa0a8, cpp, r5_state_a0a8]
  - [0xa13c, pad]
  - [0xa140, cpp, r5_state_a140]
  - [0xa1d4, pad]
  - [0xa1d8, cpp, r5_state_a1d8]
  - [0xa26c, pad]
  - [0xa270, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6e30_r5_a270]
  - [0xa928, cpp, r5_state_a928]
  - [0xa9bc, pad]
  - [0xa9c0, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6e30_r5_a9c0]
  - [0xaef8, cpp, r5_state_aef8]
  - [0xaf8c, pad]
  - [0xaf90, asm, em17_before_lifecycle_10f88_r3_4278_r4_4278_r4v2_6e30_r5_af90]
  - [0xd700, cpp, r4_state_d700]
  - [0xd74c, pad]
  - [0xd750, asm, em17_before_lifecycle_10f88_r3_4278_r4_d750]
  - [0xda38, cpp, r3_callbacks_da38]
  - [0xda40, asm, em17_before_lifecycle_10f88_r3_da40]
  - [0x10f88, cpp, lifecycle_10f88_ctor]
  - [0x10fbc, asm, lifecycle_10f88_gap1]
  - [0x10fc0, cpp, lifecycle_10f88_dtor]
  - [0x1101c, asm, lifecycle_10f88_gap2]
  - [0x11020, asm, em17_between_lifecycle_10f88_11648]
  - [0x110e8, cpp, r3_callbacks_110e8]
  - [0x110f0, asm, em17_between_lifecycle_10f88_11648_r3_110f0_r8_110f0]
  - [0x11588, cpp, r8_ptmf_11588]
  - [0x115f8, cpp, r3_callbacks_115f8]
  - [0x11638, asm, em17_between_lifecycle_10f88_11648_r3_11638]
  - [0x11640, cpp, r3_callbacks_11640]
  - [0x11648, cpp, lifecycle_11648_ctor]
  - [0x1167c, asm, lifecycle_11648_gap1]
  - [0x11680, cpp, lifecycle_11648_dtor]
  - [0x116dc, asm, lifecycle_11648_gap2]
  - [0x116e0, asm, em17_between_lifecycle_11648_11b90]
  - [0x117a0, cpp, r3_callbacks_117a0]
  - [0x117b0, asm, em17_between_lifecycle_11648_11b90_r3_117b0]
  - [0x11b90, cpp, lifecycle_11b90_ctor]
  - [0x11bc4, asm, lifecycle_11b90_gap1]
  - [0x11bc8, cpp, lifecycle_11b90_dtor]
  - [0x11c24, asm, lifecycle_11b90_gap2]
  - [0x11c28, asm, em17_tail]
  - [0x11ce8, cpp, r3_callbacks_11ce8]
  - [0x11cf8, asm, em17_tail_r3_11cf8]
  - [0x120a4, pad]
  - [0x12100, data, em17]
  - [0x18400, bss, em17]
  type: code
  vram: 0x09d15140
- - 0x18400
sha1: 2f769089d695f67e6720d5a69403a0e0d70a0aec
