name: em20
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em20
  asset_path: assets/em/em20
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em20.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em20.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em20.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em20
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em20.symbol_addrs.txt
  symbol_name_format: em20_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em20.ovl
  undefined_funcs_auto_path: build/config/em/em20.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em20.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em20
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em20_r4v2_80_r5_80]
  - [0x29e0, cpp, r5_state_29e0]
  - [0x2a74, pad]
  - [0x2a78, cpp, r4v2_state_2a78]
  - [0x2af8, asm, em20_r4v2_2af8]
  - [0x30a0, cpp, r4v2_state_30a0]
  - [0x3120, asm, em20_r4v2_3120]
  - [0x37c0, cpp, r4v2_state_37c0]
  - [0x3840, asm, em20_r4v2_3840]
  - [0x3f20, cpp, r4v2_state_3f20]
  - [0x3fa0, asm, em20_r4v2_3fa0]
  - [0x4160, cpp, r4v2_state_4160]
  - [0x41d0, asm, em20_r4v2_41d0]
  - [0x47f8, cpp, r4v2_state_47f8]
  - [0x4878, cpp, r4v2_state_4878]
  - [0x48e8, asm, em20_r4v2_48e8_r7_48e8]
  - [0x4ab0, cpp, r7_callback_4ab0]
  - [0x4b78, cpp, r4v2_state_4b78]
  - [0x4b88, cpp, r7_callback_4b88]
  - [0x4c50, asm, em20_r4v2_4b88_r7_4c50]
  - [0x4cf8, cpp, r7_callback_4cf8]
  - [0x4dc0, asm, em20_r4v2_4b88_r7_4dc0]
  - [0x5040, cpp, r3_callbacks_5040]
  - [0x5048, asm, em20_r3_5048_r4v2_5048_r7_5048]
  - [0x8850, cpp, r7_callback_8850]
  - [0x8900, cpp, r4v2_state_8900]
  - [0x8980, asm, em20_r3_5048_r4v2_8980_r5_8980_r7_8980]
  - [0x9a78, cpp, r7_callback_9a78]
  - [0x9b28, asm, em20_r3_5048_r4v2_8980_r5_8980_r7_9b28]
  - [0xac18, cpp, r5_state_ac18]
  - [0xacac, pad]
  - [0xacb0, asm, em20_r3_5048_r4v2_8980_r5_acb0]
  - [0xb770, cpp, r5_state_b770]
  - [0xb804, pad]
  - [0xb808, cpp, r5_state_b808]
  - [0xb89c, pad]
  - [0xb8a0, cpp, r5_state_b8a0]
  - [0xb934, pad]
  - [0xb938, cpp, r5_state_b938]
  - [0xb9cc, pad]
  - [0xb9d0, cpp, r3_callbacks_b9d0]
  - [0xb9d8, asm, em20_r3_b9d8_r4_b9d8_r5_b9d8]
  - [0xc018, cpp, r5_state_c018]
  - [0xc0ac, pad]
  - [0xc0b0, asm, em20_r3_b9d8_r4_b9d8_r5_c0b0_r6_c0b0]
  - [0xdda8, cpp, r6_callback_dda8]
  - [0xde2c, pad]
  - [0xde30, asm, em20_r3_b9d8_r4_b9d8_r5_c0b0_r6_de30]
  - [0xecc0, cpp, r4_state_ecc0]
  - [0xecf4, pad]
  - [0xecf8, asm, em20_r3_b9d8_r4_ecf8_r4v2_ecf8]
  - [0xf048, cpp, r4v2_state_f048]
  - [0xf080, asm, em20_r3_b9d8_r4_ecf8_r4v2_f080]
  - [0x124d8, cpp, r3_callbacks_124d8]
  - [0x124e8, asm, em20_r3_124e8]
  - [0x125f8, cpp, r3_callbacks_125f8]
  - [0x12600, asm, em20_r3_12600_r8_12600]
  - [0x16118, cpp, r8_ptmf_16118]
  - [0x16188, asm, em20_r3_12600_r8_16188]
  - [0x16190, cpp, r3_callbacks_16190]
  - [0x161d8, cpp, r3_lifecycle_161d8_dtor]
  - [0x16234, pad]
  - [0x16280, data, em20]
  - [0x22e00, bss, em20]
  type: code
  vram: 0x09d15140
- - 0x22e00
sha1: 109d5fc53580595c4932ad8b702f3fc9cecfbcb2
