name: em33
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em33
  asset_path: assets/em/em33
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em33.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em33.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em33.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em33
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em33.symbol_addrs.txt
  symbol_name_format: em33_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em33.ovl
  undefined_funcs_auto_path: build/config/em/em33.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em33.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em33
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em33_before_lifecycle_5cd0]
  - [0x5a0, cpp, r3_callbacks_5a0]
  - [0x5a8, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_5a8_r4v2_5a8]
  - [0x610, cpp, r4v2_state_610]
  - [0x67c, pad]
  - [0x680, cpp, r4v2_state_680]
  - [0x6ec, pad]
  - [0x6f0, cpp, r4v2_state_6f0]
  - [0x75c, pad]
  - [0x760, cpp, r4v2_state_760]
  - [0x7cc, pad]
  - [0x7d0, cpp, r4v2_state_7d0]
  - [0x83c, pad]
  - [0x840, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_5a8_r4v2_840]
  - [0xb28, cpp, r4v2_state_b28]
  - [0xb94, pad]
  - [0xb98, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_5a8_r4v2_b98]
  - [0x1428, cpp, r4v2_state_1428]
  - [0x1494, pad]
  - [0x1498, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_5a8_r4v2_1498]
  - [0x2000, cpp, r4v2_state_2000]
  - [0x206c, pad]
  - [0x2070, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_5a8_r4v2_2070]
  - [0x35b0, cpp, r4_state_35b0]
  - [0x35fc, pad]
  - [0x3600, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_3600]
  - [0x3bc8, cpp, r4_state_3bc8]
  - [0x3c14, pad]
  - [0x3c18, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_3c18]
  - [0x3d48, cpp, r4_state_3d48]
  - [0x3d7c, pad]
  - [0x3d80, asm, em33_before_lifecycle_5cd0_r3_5a8_r4_3d80]
  - [0x4dd8, cpp, r3_callbacks_4dd8]
  - [0x4de0, asm, em33_before_lifecycle_5cd0_r3_4de0]
  - [0x5cd0, cpp, lifecycle_5cd0_ctor]
  - [0x5d04, asm, lifecycle_5cd0_gap1]
  - [0x5d08, cpp, lifecycle_5cd0_dtor]
  - [0x5d64, asm, lifecycle_5cd0_gap2]
  - [0x5d68, asm, em33_between_lifecycle_5cd0_63b0]
  - [0x5e38, cpp, r3_callbacks_5e38]
  - [0x5e48, asm, em33_between_lifecycle_5cd0_63b0_r3_5e48]
  - [0x63b0, cpp, lifecycle_63b0_ctor]
  - [0x63e4, asm, lifecycle_63b0_gap1]
  - [0x63e8, cpp, lifecycle_63b0_dtor]
  - [0x6444, asm, lifecycle_63b0_gap2]
  - [0x6448, asm, em33_tail]
  - [0x6d08, pad]
  - [0x6d80, data, em33]
  - [0xc600, bss, em33]
  type: code
  vram: 0x09d15140
- - 0xc600
sha1: c8778f6244051961cf6fb2585129c6de393b185c
