name: em40
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em40
  asset_path: assets/em/em40
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em40.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em40.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em40.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em40
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em40.symbol_addrs.txt
  symbol_name_format: em40_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em40.ovl
  undefined_funcs_auto_path: build/config/em/em40.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em40.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em40
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em40_before_lifecycle_14da0_r4v2_80]
  - [0xb38, cpp, r4v2_state_b38]
  - [0xb70, asm, em40_before_lifecycle_14da0_r4v2_b70]
  - [0x2900, cpp, r3_callbacks_2900]
  - [0x2908, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_2908]
  - [0x3060, cpp, r4v2_state_3060]
  - [0x30e0, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_30e0]
  - [0x33f8, cpp, r4v2_state_33f8]
  - [0x3478, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_3478]
  - [0x3b68, cpp, r4v2_state_3b68]
  - [0x3bd8, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_3bd8]
  - [0x40a8, cpp, r4v2_state_40a8]
  - [0x4128, cpp, r4v2_state_4128]
  - [0x4198, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_4198_r7_4198]
  - [0x4258, cpp, r7_callback_4258]
  - [0x4320, cpp, r7_callback_4320]
  - [0x43e8, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_4198_r7_43e8]
  - [0x4490, cpp, r7_callback_4490]
  - [0x4558, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_4198_r7_4558]
  - [0x4600, cpp, r7_callback_4600]
  - [0x46c8, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_4198_r7_46c8]
  - [0x6ff0, cpp, r7_callback_6ff0]
  - [0x70a0, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_4198_r7_70a0]
  - [0x7270, cpp, r7_callback_7270]
  - [0x7320, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_4198_r7_7320]
  - [0x7518, cpp, r5_state_7518]
  - [0x75ac, pad]
  - [0x75b0, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_4198_r5_75b0]
  - [0x8418, cpp, r4v2_state_8418]
  - [0x8498, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_8498_r5_8498]
  - [0xab78, cpp, r5_state_ab78]
  - [0xac0c, pad]
  - [0xac10, cpp, r5_state_ac10]
  - [0xaca4, pad]
  - [0xaca8, cpp, r5_state_aca8]
  - [0xad3c, pad]
  - [0xad40, cpp, r5_state_ad40]
  - [0xadd4, pad]
  - [0xadd8, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_8498_r5_add8]
  - [0xb4b0, cpp, r5_state_b4b0]
  - [0xb544, pad]
  - [0xb548, asm, em40_before_lifecycle_14da0_r3_2908_r4_2908_r4v2_8498_r5_b548_r6_b548]
  - [0xeb58, cpp, r6_callback_eb58]
  - [0xebdc, pad]
  - [0xebe0, cpp, r4_state_ebe0]
  - [0xec14, pad]
  - [0xec18, asm, em40_before_lifecycle_14da0_r3_2908_r4_ec18]
  - [0x12218, cpp, r3_callbacks_12218]
  - [0x12220, asm, em40_before_lifecycle_14da0_r3_12220]
  - [0x14da0, cpp, lifecycle_14da0_ctor]
  - [0x14dd4, asm, lifecycle_14da0_gap1]
  - [0x14dd8, cpp, lifecycle_14da0_dtor]
  - [0x14e34, asm, lifecycle_14da0_gap2]
  - [0x14e38, asm, em40_between_lifecycle_14da0_15418]
  - [0x14ec8, cpp, r3_callbacks_14ec8]
  - [0x14ed0, asm, em40_between_lifecycle_14da0_15418_r3_14ed0_r8_14ed0]
  - [0x15358, cpp, r8_ptmf_15358]
  - [0x153c8, cpp, r3_callbacks_153c8]
  - [0x15408, asm, em40_between_lifecycle_14da0_15418_r3_15408]
  - [0x15410, cpp, r3_callbacks_15410]
  - [0x15418, cpp, lifecycle_15418_ctor]
  - [0x1544c, asm, lifecycle_15418_gap1]
  - [0x15450, cpp, lifecycle_15418_dtor]
  - [0x154ac, asm, lifecycle_15418_gap2]
  - [0x154b0, asm, em40_tail]
  - [0x15570, cpp, r3_callbacks_15570]
  - [0x15580, asm, em40_tail_r3_15580]
  - [0x1667c, pad]
  - [0x16680, data, em40]
  - [0x21b80, bss, em40]
  type: code
  vram: 0x09d15140
- - 0x21b80
sha1: 20146435bcd87dccc12a8c9ca472334f52ec1656
