name: em54
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em54
  asset_path: assets/em/em54
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em54.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em54.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em54.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em54
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em54.symbol_addrs.txt
  symbol_name_format: em54_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em54.ovl
  undefined_funcs_auto_path: build/config/em/em54.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em54.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em54
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em54_before_lifecycle_2ed0]
  - [0x2ed0, cpp, lifecycle_2ed0_ctor]
  - [0x2f04, asm, lifecycle_2ed0_gap1]
  - [0x2f08, cpp, lifecycle_2ed0_dtor]
  - [0x2f64, asm, lifecycle_2ed0_gap2]
  - [0x2f68, asm, em54_between_lifecycle_2ed0_3618]
  - [0x2ff8, cpp, r3_callbacks_2ff8]
  - [0x3000, asm, em54_between_lifecycle_2ed0_3618_r3_3000_r8_3000]
  - [0x3558, cpp, r8_ptmf_3558]
  - [0x35c8, cpp, r3_callbacks_35c8]
  - [0x3608, asm, em54_between_lifecycle_2ed0_3618_r3_3608]
  - [0x3610, cpp, r3_callbacks_3610]
  - [0x3618, cpp, lifecycle_3618_ctor]
  - [0x364c, asm, lifecycle_3618_gap1]
  - [0x3650, cpp, lifecycle_3618_dtor]
  - [0x36ac, asm, lifecycle_3618_gap2]
  - [0x36b0, asm, em54_between_lifecycle_3618_19f90]
  - [0x3740, cpp, r3_callbacks_3740]
  - [0x3748, asm, em54_between_lifecycle_3618_19f90_r3_3748_r8_3748]
  - [0x3d60, cpp, r8_ptmf_3d60]
  - [0x3dd0, cpp, r3_callbacks_3dd0]
  - [0x3e10, asm, em54_between_lifecycle_3618_19f90_r3_3e10]
  - [0x3e18, cpp, r3_callbacks_3e18]
  - [0x3e20, asm, em54_between_lifecycle_3618_19f90_r3_3e20]
  - [0x4ae0, cpp, r3_callbacks_4ae0]
  - [0x4b28, asm, em54_between_lifecycle_3618_19f90_r3_4b28]
  - [0x5230, cpp, r3_callbacks_5230]
  - [0x5238, asm, em54_between_lifecycle_3618_19f90_r3_5238_r4_5238]
  - [0x5bd0, cpp, r4_state_5bd0]
  - [0x5be8, cpp, r4v2_state_5be8]
  - [0x5c38, asm, em54_between_lifecycle_3618_19f90_r3_5238_r4_5be8_r4v2_5c38]
  - [0x67e0, cpp, r3_callbacks_67e0]
  - [0x67e8, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_67e8]
  - [0x7500, cpp, r4v2_state_7500]
  - [0x7588, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_7588]
  - [0x79d0, cpp, r4v2_state_79d0]
  - [0x7a48, cpp, r4v2_state_7a48]
  - [0x7ac0, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_7ac0]
  - [0x82e0, cpp, r4v2_state_82e0]
  - [0x8368, cpp, r4v2_state_8368]
  - [0x83f0, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_83f0]
  - [0xc5f0, cpp, r4v2_state_c5f0]
  - [0xc678, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_c678_r5_c678]
  - [0xd698, cpp, r5_state_d698]
  - [0xd734, pad]
  - [0xd738, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_c678_r5_d738_r6_d738]
  - [0xd820, cpp, r6_callback_d820]
  - [0xd8bc, pad]
  - [0xd8c0, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_c678_r5_d738_r6_d8c0]
  - [0xe230, cpp, r5_state_e230]
  - [0xe2cc, pad]
  - [0xe2d0, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_c678_r5_e2d0_r6_e2d0]
  - [0x11030, cpp, r6_callback_11030]
  - [0x110b4, pad]
  - [0x110b8, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_67e8_r4v2_c678_r5_e2d0_r6_110b8]
  - [0x11170, cpp, r4_state_11170]
  - [0x111a4, pad]
  - [0x111a8, asm, em54_between_lifecycle_3618_19f90_r3_67e8_r4_111a8]
  - [0x147f8, cpp, r3_callbacks_147f8]
  - [0x14800, asm, em54_between_lifecycle_3618_19f90_r3_14800]
  - [0x149b0, cpp, r3_lifecycle_149b0_dtor]
  - [0x14a0c, pad]
  - [0x14a10, cpp, r3_callbacks_14a10]
  - [0x14a18, asm, em54_between_lifecycle_3618_19f90_r3_14a18]
  - [0x19f90, cpp, lifecycle_19f90_ctor]
  - [0x19fc4, asm, lifecycle_19f90_gap1]
  - [0x19fc8, cpp, lifecycle_19f90_dtor]
  - [0x1a024, asm, lifecycle_19f90_gap2]
  - [0x1a028, asm, em54_tail]
  - [0x1a160, cpp, r3_callbacks_1a160]
  - [0x1a170, asm, em54_tail_r3_1a170]
  - [0x1a9ac, pad]
  - [0x1aa00, data, em54]
  - [0x29800, bss, em54]
  type: code
  vram: 0x09d15140
- - 0x29800
sha1: 0eab70d231e41a6e02f78169d7f0084b45c04491
