name: em55
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em55
  asset_path: assets/em/em55
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em55.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em55.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em55.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em55
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em55.symbol_addrs.txt
  symbol_name_format: em55_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em55.ovl
  undefined_funcs_auto_path: build/config/em/em55.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em55.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em55
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, cpp, ctor]
  - [0xb4, asm, ctor_gap]
  - [0xb8, cpp, dtor]
  - [0x114, asm, dtor_gap]
  - [0x118, cpp, init]
  - [0x1c0, cpp, noop]
  - [0x1c8, asm, em55_before_action_timer]
  - [0xfe8, cpp, r3_callbacks_fe8]
  - [0xff0, asm, em55_before_action_timer_r3_ff0]
  - [0x1d48, cpp, r3_callbacks_1d48]
  - [0x1d50, asm, em55_before_action_timer_r3_1d50_r4_1d50_r4v2_1d50_r5_1d50]
  - [0x27c8, cpp, r5_state_27c8]
  - [0x2848, cpp, r5_state_2848]
  - [0x28c8, cpp, r5_state_28c8]
  - [0x2948, cpp, r4v2_state_2948]
  - [0x29c8, asm, em55_before_action_timer_r3_1d50_r4_1d50_r4v2_29c8]
  - [0x3430, cpp, r4_state_3430]
  - [0x347c, pad]
  - [0x3480, asm, em55_before_action_timer_r3_1d50_r4_3480]
  - [0x3b10, cpp, action_timer]
  - [0x3bd8, asm, em55_before_sync]
  - [0x64d8, cpp, r3_callbacks_64d8]
  - [0x64e0, asm, em55_before_sync_r3_64e0]
  - [0x6540, cpp, r3_callbacks_6540]
  - [0x6550, asm, em55_before_sync_r3_6550]
  - [0x6980, cpp, r3_callbacks_6980]
  - [0x6988, asm, em55_before_sync_r3_6988]
  - [0x6a10, cpp, game_state]
  - [0x6b20, asm, em55_tail]
  - [0x6bc0, cpp, r3_lifecycle_6bc0_dtor]
  - [0x6c1c, pad]
  - [0x6c20, cpp, r3_callbacks_6c20]
  - [0x6c28, asm, em55_tail_r3_6c28]
  - [0xe5d4, pad]
  - [0xe600, data, em55]
  - [0x12180, bss, em55]
  type: code
  vram: 0x09d15140
- - 0x12180
sha1: e4bc7b6a8e55b326a44dec1bc1521a21a2dfab7c
