name: em58
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em58
  asset_path: assets/em/em58
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em58.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em58.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em58.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em58
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em58.symbol_addrs.txt
  symbol_name_format: em58_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em58.ovl
  undefined_funcs_auto_path: build/config/em/em58.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em58.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em58
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, em58_before_b770]
  - [0x190, cpp, r3_callbacks_190]
  - [0x198, asm, em58_before_b770_r3_198]
  - [0x1648, cpp, r3_callbacks_1648]
  - [0x1650, asm, em58_before_b770_r3_1650_r4_1650_r4v2_1650]
  - [0x1870, cpp, r4v2_state_1870]
  - [0x18f0, cpp, r6_callback_18f0]
  - [0x1990, asm, em58_before_b770_r3_1650_r4_1650_r4v2_18f0_r6_1990]
  - [0x1ed0, cpp, r6_callback_1ed0]
  - [0x1f50, asm, em58_before_b770_r3_1650_r4_1650_r4v2_18f0_r6_1f50]
  - [0x53a0, cpp, r4_state_53a0]
  - [0x53ec, pad]
  - [0x53f0, asm, em58_before_b770_r3_1650_r4_53f0]
  - [0x5c38, cpp, r4_state_5c38]
  - [0x5c84, pad]
  - [0x5c88, asm, em58_before_b770_r3_1650_r4_5c88]
  - [0x63d8, cpp, r3_callbacks_63d8]
  - [0x63e0, asm, em58_before_b770_r3_63e0]
  - [0x77b0, cpp, r3_callbacks_77b0]
  - [0x77c0, cpp, r4v2_state_77c0]
  - [0x77d8, cpp, r4_state_77d8]
  - [0x77ec, pad]
  - [0x77f0, cpp, r4_state_77f0]
  - [0x780c, pad]
  - [0x7810, cpp, r4_state_7810]
  - [0x782c, pad]
  - [0x7830, cpp, r4_state_7830]
  - [0x784c, pad]
  - [0x7850, cpp, r4_state_7850]
  - [0x786c, pad]
  - [0x7870, cpp, r4_state_7870]
  - [0x7890, cpp, r4_state_7890]
  - [0x78b0, cpp, r4_state_78b0]
  - [0x78d0, asm, em58_before_b770_r3_77c0_r4_78d0]
  - [0x7970, cpp, r3_lifecycle_7970_dtor]
  - [0x79cc, pad]
  - [0x79d0, cpp, r3_callbacks_79d0]
  - [0x79d8, asm, em58_before_b770_r3_79d8]
  - [0xb770, cpp, lifecycle_b770_ctor]
  - [0xb7a4, asm, lifecycle_b770_gap1]
  - [0xb7a8, cpp, lifecycle_b770_dtor]
  - [0xb804, asm, lifecycle_b770_gap2]
  - [0xb808, asm, em58_between_b770_bc28]
  - [0xb898, cpp, r3_callbacks_b898]
  - [0xb8a0, asm, em58_between_b770_bc28_r3_b8a0_r8_b8a0]
  - [0xbb68, cpp, r8_ptmf_bb68]
  - [0xbbd8, cpp, r3_callbacks_bbd8]
  - [0xbc18, asm, em58_between_b770_bc28_r3_bc18]
  - [0xbc20, cpp, r3_callbacks_bc20]
  - [0xbc28, cpp, lifecycle_bc28_ctor]
  - [0xbc5c, asm, lifecycle_bc28_gap1]
  - [0xbc60, cpp, lifecycle_bc28_dtor]
  - [0xbcbc, asm, lifecycle_bc28_gap2]
  - [0xbcc0, asm, em58_between_bc28_c780]
  - [0xc780, cpp, lifecycle_c780_ctor]
  - [0xc7b4, asm, lifecycle_c780_gap1]
  - [0xc7b8, cpp, lifecycle_c780_dtor]
  - [0xc814, asm, lifecycle_c780_gap2]
  - [0xc818, asm, em58]
  - [0xc8d8, cpp, r3_callbacks_c8d8]
  - [0xc8e8, asm, em58_r3_c8e8]
  - [0xd2c0, pad]
  - [0xd300, data, em58]
  - [0x10e80, bss, em58]
  type: code
  vram: 0x09d15140
- - 0x10e80
sha1: 50265021f08fdd0a20d945b3899f6056611914f2
