name: em75
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em75
  asset_path: assets/em/em75
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em75.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em75.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em75.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em75
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em75.symbol_addrs.txt
  symbol_name_format: em75_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em75.ovl
  undefined_funcs_auto_path: build/config/em/em75.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em75.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x100
  name: em75
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, cpp, r3_lifecycle_80_dtor]
  - [0xdc, pad]
  - [0xe0, asm, em75_before_16a8]
  - [0x190, cpp, r3_callbacks_190]
  - [0x1a0, asm, em75_before_16a8_r3_1a0]
  - [0x16a8, cpp, lifecycle_16a8_ctor]
  - [0x16dc, asm, lifecycle_16a8_gap1]
  - [0x16e0, cpp, lifecycle_16a8_dtor]
  - [0x173c, asm, lifecycle_16a8_gap2]
  - [0x1740, asm, em75_between_16a8_26f8]
  - [0x1800, cpp, r3_callbacks_1800]
  - [0x1810, asm, em75_between_16a8_26f8_r3_1810]
  - [0x26f8, cpp, lifecycle_26f8_ctor]
  - [0x272c, asm, lifecycle_26f8_gap1]
  - [0x2730, cpp, lifecycle_26f8_dtor]
  - [0x278c, asm, lifecycle_26f8_gap2]
  - [0x2790, asm, em75_before_32c0]
  - [0x2910, cpp, r3_callbacks_2910]
  - [0x2920, asm, em75_before_32c0_r3_2920]
  - [0x32c0, cpp, lifecycle_32c0_ctor]
  - [0x32f4, asm, lifecycle_32c0_gap1]
  - [0x32f8, cpp, lifecycle_32c0_dtor]
  - [0x3354, asm, lifecycle_32c0_gap2]
  - [0x3358, asm, em75_between_32c0_4b58]
  - [0x3428, cpp, r3_callbacks_3428]
  - [0x3438, asm, em75_between_32c0_4b58_r3_3438]
  - [0x4b58, cpp, lifecycle_4b58_ctor]
  - [0x4b8c, asm, lifecycle_4b58_gap1]
  - [0x4b90, cpp, lifecycle_4b58_dtor]
  - [0x4bec, asm, lifecycle_4b58_gap2]
  - [0x4bf0, asm, em75_between_4b58_6e90]
  - [0x4cc0, cpp, r3_callbacks_4cc0]
  - [0x4cd0, asm, em75_between_4b58_6e90_r3_4cd0]
  - [0x6e90, cpp, lifecycle_6e90_ctor]
  - [0x6ec4, asm, lifecycle_6e90_gap1]
  - [0x6ec8, cpp, lifecycle_6e90_dtor]
  - [0x6f24, asm, lifecycle_6e90_gap2]
  - [0x6f28, asm, em75_prefix]
  - [0x6ff8, cpp, r3_callbacks_6ff8]
  - [0x7008, asm, em75_prefix_r3_7008]
  - [0x7a90, cpp, vtable_07_ctor]
  - [0x7ac4, asm, vtable_07_gap1]
  - [0x7ac8, cpp, vtable_07_dtor]
  - [0x7b24, asm, vtable_07_gap2]
  - [0x7b28, cpp, vtable_07_effect]
  - [0x7bd8, asm, em75_before_8520]
  - [0x8520, cpp, lifecycle_8520_ctor]
  - [0x8554, asm, lifecycle_8520_gap1]
  - [0x8558, cpp, lifecycle_8520_dtor]
  - [0x85b4, asm, lifecycle_8520_gap2]
  - [0x85b8, asm, em75_between_8520_8ff8]
  - [0x86a0, cpp, r3_callbacks_86a0]
  - [0x86b0, asm, em75_between_8520_8ff8_r3_86b0]
  - [0x8ff8, cpp, lifecycle_8ff8_ctor]
  - [0x902c, asm, lifecycle_8ff8_gap1]
  - [0x9030, cpp, lifecycle_8ff8_dtor]
  - [0x908c, asm, lifecycle_8ff8_gap2]
  - [0x9090, asm, em75_between_8ff8_9a78]
  - [0x9a78, cpp, lifecycle_9a78_ctor]
  - [0x9aac, asm, lifecycle_9a78_gap1]
  - [0x9ab0, cpp, lifecycle_9a78_dtor]
  - [0x9b0c, asm, lifecycle_9a78_gap2]
  - [0x9b10, asm, em75_between_9a78_a360]
  - [0x9be0, cpp, r3_callbacks_9be0]
  - [0x9bf0, asm, em75_between_9a78_a360_r3_9bf0]
  - [0xa360, cpp, lifecycle_a360_ctor]
  - [0xa394, asm, lifecycle_a360_gap1]
  - [0xa398, cpp, lifecycle_a360_dtor]
  - [0xa3f4, asm, lifecycle_a360_gap2]
  - [0xa3f8, asm, em75_between_a360_b1f0]
  - [0xa4c0, cpp, r3_callbacks_a4c0]
  - [0xa4d0, asm, em75_between_a360_b1f0_r3_a4d0]
  - [0xb1f0, cpp, lifecycle_b1f0_ctor]
  - [0xb224, asm, lifecycle_b1f0_gap1]
  - [0xb228, cpp, lifecycle_b1f0_dtor]
  - [0xb284, asm, lifecycle_b1f0_gap2]
  - [0xb288, asm, em75_middle]
  - [0xb348, cpp, r3_callbacks_b348]
  - [0xb358, asm, em75_middle_r3_b358_r4_b358_r4v2_b358]
  - [0xc3a0, cpp, r4v2_state_c3a0]
  - [0xc428, asm, em75_middle_r3_b358_r4_b358_r4v2_c428]
  - [0xc908, cpp, r4v2_state_c908]
  - [0xc990, asm, em75_middle_r3_b358_r4_b358_r4v2_c990]
  - [0xf020, cpp, r4_state_f020]
  - [0xf038, cpp, r4v2_state_f038]
  - [0xf088, asm, em75_middle_r3_b358_r4_f038_r4v2_f088]
  - [0x12b58, cpp, r4v2_state_12b58]
  - [0x12be0, cpp, r4v2_state_12be0]
  - [0x12c68, asm, em75_middle_r3_b358_r4_f038_r4v2_12c68_r5_12c68]
  - [0x15448, cpp, r5_state_15448]
  - [0x154e4, pad]
  - [0x154e8, cpp, r5_state_154e8]
  - [0x15584, pad]
  - [0x15588, cpp, r5_state_15588]
  - [0x15624, pad]
  - [0x15628, cpp, r5_state_15628]
  - [0x156c4, pad]
  - [0x156c8, asm, em75_middle_r3_b358_r4_f038_r4v2_12c68_r5_156c8]
  - [0x15bb8, cpp, r5_state_15bb8]
  - [0x15c54, pad]
  - [0x15c58, asm, em75_middle_r3_b358_r4_f038_r4v2_12c68_r5_15c58]
  - [0x15e90, cpp, r5_state_15e90]
  - [0x15f2c, pad]
  - [0x15f30, asm, em75_middle_r3_b358_r4_f038_r4v2_12c68_r5_15f30]
  - [0x16df8, cpp, r4v2_state_16df8]
  - [0x16e70, asm, em75_middle_r3_b358_r4_f038_r4v2_16e70_r5_16e70]
  - [0x17008, cpp, r5_state_17008]
  - [0x170a4, pad]
  - [0x170a8, asm, em75_middle_r3_b358_r4_f038_r4v2_16e70_r5_170a8_r6_170a8]
  - [0x1afc0, cpp, r6_callback_1afc0]
  - [0x1b060, asm, em75_middle_r3_b358_r4_f038_r4v2_16e70_r5_170a8_r6_1b060]
  - [0x1b170, cpp, r4_state_1b170]
  - [0x1b1a4, pad]
  - [0x1b1a8, asm, em75_middle_r3_b358_r4_1b1a8]
  - [0x23198, cpp, r3_callbacks_23198]
  - [0x231a0, asm, em75_middle_r3_231a0]
  - [0x25230, cpp, r3_callbacks_25230]
  - [0x25238, asm, em75_middle_r3_25238]
  - [0x31100, cpp, vtable_13_ctor]
  - [0x31134, asm, vtable_13_gap1]
  - [0x31138, cpp, vtable_13_dtor]
  - [0x31194, asm, vtable_13_gap2]
  - [0x31198, cpp, vtable_13_init]
  - [0x312c0, cpp, vtable_13_noop]
  - [0x312c8, asm, em75_head_1_r8_312c8]
  - [0x31fa8, cpp, r8_ptmf_31fa8]
  - [0x32018, asm, em75_head_1_r8_32018]
  - [0x32020, cpp, vtable_14_ctor]
  - [0x3205c, asm, vtable_14_gap1]
  - [0x32060, cpp, vtable_14_dtor]
  - [0x320bc, asm, vtable_14_gap2]
  - [0x320c0, cpp, vtable_14_init]
  - [0x32168, cpp, vtable_14_noop]
  - [0x32170, asm, em75_head_b_before_dispatch_r8_32170]
  - [0x32788, cpp, r8_ptmf_32788]
  - [0x327f8, cpp, dispatch_327f8]
  - [0x32864, asm, em75_head_b_gap]
  - [0x32868, asm, em75_head_b]
  - [0x34b90, cpp, vtable_15_dispatch]
  - [0x34c20, asm, em75_before_34de0]
  - [0x34de0, cpp, lifecycle_34de0_ctor]
  - [0x34e14, asm, lifecycle_34de0_gap1]
  - [0x34e18, cpp, lifecycle_34de0_dtor]
  - [0x34e74, asm, lifecycle_34de0_gap2]
  - [0x34e78, asm, em75_tail_before_dispatch_r8_34e78]
  - [0x35748, cpp, r8_ptmf_35748]
  - [0x357b8, cpp, dispatch_357b8]
  - [0x35824, asm, em75_tail_gap]
  - [0x35828, asm, em75_tail]
  - [0x37720, cpp, r3_callbacks_37720]
  - [0x37750, asm, em75_tail_r3_37750]
  - [0x378a8, pad]
  - [0x37900, data, em75]
  - [0x48d80, bss, em75]
  type: code
  vram: 0x09d15140
- - 0x48d80
sha1: 488525f80f6be3c2564c5262f165c936857e3ad3
