name: em82
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/em/em82
  asset_path: assets/em/em82
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: em82.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/em/em82.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/em/em82.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/em/em82
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/em/em82.symbol_addrs.txt
  symbol_name_format: em82_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/em/em82.ovl
  undefined_funcs_auto_path: build/config/em/em82.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/em/em82.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x80
  name: em82
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, cpp, lifecycle_80_ctor]
  - [0xb4, asm, lifecycle_80_gap1]
  - [0xb8, cpp, lifecycle_80_dtor]
  - [0x114, asm, lifecycle_80_gap2]
  - [0x118, asm, em82_tail]
  - [0x210, cpp, r3_callbacks_210]
  - [0x220, asm, em82_tail_r3_220_r4v2_220]
  - [0x3708, cpp, r4v2_state_3708]
  - [0x3788, asm, em82_tail_r3_220_r4v2_3788]
  - [0x3880, cpp, r4v2_state_3880]
  - [0x3900, asm, em82_tail_r3_220_r4v2_3900]
  - [0x3d60, cpp, r4v2_state_3d60]
  - [0x3de0, asm, em82_tail_r3_220_r4v2_3de0]
  - [0x4450, cpp, r4v2_state_4450]
  - [0x44c0, asm, em82_tail_r3_220_r4v2_44c0]
  - [0x4ae8, cpp, r4v2_state_4ae8]
  - [0x4b68, cpp, r4v2_state_4b68]
  - [0x4bd8, asm, em82_tail_r3_220_r4v2_4bd8_r7_4bd8]
  - [0x4d30, cpp, r7_callback_4d30]
  - [0x4df8, cpp, r4v2_state_4df8]
  - [0x4e08, cpp, r7_callback_4e08]
  - [0x4ed0, asm, em82_tail_r3_220_r4v2_4e08_r7_4ed0]
  - [0x51f8, cpp, r3_callbacks_51f8]
  - [0x5200, asm, em82_tail_r3_5200]
  - [0x79e0, cpp, r3_callbacks_79e0]
  - [0x79e8, asm, em82_tail_r3_79e8_r5_79e8_r7_79e8]
  - [0xae30, cpp, r7_callback_ae30]
  - [0xaee0, asm, em82_tail_r3_79e8_r5_79e8_r7_aee0]
  - [0xb478, cpp, r5_state_b478]
  - [0xb50c, pad]
  - [0xb510, asm, em82_tail_r3_79e8_r5_b510]
  - [0xbd40, cpp, r5_state_bd40]
  - [0xbdd4, pad]
  - [0xbdd8, cpp, r5_state_bdd8]
  - [0xbe6c, pad]
  - [0xbe70, cpp, r5_state_be70]
  - [0xbf04, pad]
  - [0xbf08, cpp, r5_state_bf08]
  - [0xbf9c, pad]
  - [0xbfa0, cpp, r3_callbacks_bfa0]
  - [0xbfa8, asm, em82_tail_r3_bfa8_r5_bfa8]
  - [0xc5e8, cpp, r5_state_c5e8]
  - [0xc67c, pad]
  - [0xc680, asm, em82_tail_r3_bfa8_r5_c680]
  - [0xcb00, cpp, r3_callbacks_cb00]
  - [0xcb08, asm, em82_tail_r3_cb08_r4_cb08_r5_cb08]
  - [0xce38, cpp, r5_state_ce38]
  - [0xcecc, pad]
  - [0xced0, asm, em82_tail_r3_cb08_r4_cb08_r5_ced0_r6_ced0]
  - [0xde48, cpp, r6_callback_de48]
  - [0xdee8, asm, em82_tail_r3_cb08_r4_cb08_r5_ced0_r6_dee8]
  - [0xf698, cpp, r4_state_f698]
  - [0xf6cc, pad]
  - [0xf6d0, asm, em82_tail_r3_cb08_r4_f6d0_r4v2_f6d0]
  - [0xfa20, cpp, r4v2_state_fa20]
  - [0xfa58, asm, em82_tail_r3_cb08_r4_f6d0_r4v2_fa58]
  - [0x12938, cpp, r3_callbacks_12938]
  - [0x12948, asm, em82_tail_r3_12948]
  - [0x12a58, cpp, r3_callbacks_12a58]
  - [0x12a60, asm, em82_tail_r3_12a60_r8_12a60]
  - [0x16578, cpp, r8_ptmf_16578]
  - [0x165e8, asm, em82_tail_r3_12a60_r8_165e8]
  - [0x165f0, cpp, r3_callbacks_165f0]
  - [0x16638, cpp, r3_lifecycle_16638_dtor]
  - [0x16694, pad]
  - [0x16700, data, em82]
  - [0x1e480, bss, em82]
  type: code
  vram: 0x09d15140
- - 0x1e480
sha1: b9e305f8e469297c58651eadb1002795ebbaa435
