name: option_task
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/task/option_task
  asset_path: assets/task/option_task
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: option_task.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/modules/task/option_task.ovl.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/task/option_task.reloc_addrs.txt
  rodata_string_guesser_level: 0
  src_path: src/task/option_task
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/task/option_task.symbol_addrs.txt
  target_path: modules/task/option_task.ovl
  undefined_funcs_auto_path: build/config/task/option_task.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/task/option_task.undefined_syms_auto.txt
segments:
- align: 4
  name: option_task.ovl_header
  start: 0x0
  subalign: 4
  subsegments:
  - [0x0, data]
  type: code
  vram: 0x09a5a580
- align: 4
  bss_size: 0x400
  name: option_task
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm]
  - [0x17d8, int4]
  - [0x1900, bss]
  type: code
  vram: 0x09a5a5c0
- - 0x1900
sha1: bcaf2dc9552b3db30da2c6cfcdf1ad23f0accc02
