asset_path: assets/eboot
target_path: modules/eboot.elf
start: 0x25b4
vram: 0x08804000
segments:
  - [0x12fde4, cameraop]
  - [0x12ff54, cameraop]
  - [0x12ff54, cameraop]
  - [0x12ff9c, cameraop]
  - [0x12ffe0, cameraop]
  - [0x130024, cameraop]
  - [0x1301a8, cameraop]
  - [0x130274, cameraop]
  - [0x1303a0, cameraop]
  - [0x130528, cameraop]
  - [0x1305b8, cameraop]
  - [0x1308bc, cameraop]
  - [0x130b1c, cameraop]
  - [0x130e14, cameraop]
  - [0x13140c, cameraop]
  - [0x131990, cameraop]
  - [0x131e04, cameraop]
  - [0x132300, cameraop]
  - [0x132674, cameraop]
  - [0x132c14, cameraop]
  - [0x132c28, cameraop]
  - [0x132d8c, cameraop]
  - [0x132e9c, cameraop]
  - [0x132fac, cameraop]
  - [0x1330bc, cameraop]
  - [0x1331cc, cameraop]
  - [0x1332dc, cameraop]
  - [0x1333ec, cameraop]
  - [0x1334f8, cameraop]
  - [0x13366c, cameraop]
  - [0x133784, cameraop]
  - [0x1338f8, cameraop]
  - [0x133a80, cameraop]
  - [0x133bf4, cameraop]
  - [0x133d10, cameraop]
