name: game_sub
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/sub/game_sub
  asset_path: assets/sub/game_sub
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: game_sub.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/sub/game_sub.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/sub/game_sub.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/sub/game_sub
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/sub/game_sub.symbol_addrs.txt
  symbol_name_format: game_sub_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/sub/game_sub.ovl
  undefined_funcs_auto_path: build/config/sub/game_sub.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/sub/game_sub.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x1ea00
  name: game_sub
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asmtu, lb_event]
  - [0x1cb8, asmtu, kitchen]
  - [0x6540, asmtu, training]
  - [0xf8f8, asmtu, farm_sys]
  - [0x11fe8, asmtu, dialog]
  - [0x12948, asmtu, effect_manager]
  - [0x1b1b8, asmtu, hit]
  - [0x1d818, asmtu, hit_sub0]
  - [0x28ae8, asmtu, hitcheck]
  - [0x3dac8, asmtu, gamestage]
  - [0x3db18, asmtu, effect_handle]
  - [0x3db70, asmtu, effect_base]
  - [0x3df40, asmtu, effect00]
  - [0x3e910, asmtu, effect01]
  - [0x3f8b8, asmtu, effect02]
  - [0x41b40, asmtu, effect03]
  - [0x42650, asmtu, effect04]
  - [0x46450, asmtu, effect05]
  - [0x47a10, asmtu, effect06]
  - [0x4b940, asmtu, effect07]
  - [0x4de18, asmtu, effect08]
  - [0x4f148, asmtu, effect09]
  - [0x505e0, asmtu, effect10]
  - [0x51208, asmtu, effect11]
  - [0x52118, asmtu, effect12]
  - [0x55c88, asmtu, effect13]
  - [0x5bfc0, asmtu, effect14]
  - [0x5fee8, asmtu, effect15]
  - [0x622f8, asmtu, effect16]
  - [0x65ff0, asmtu, effect17]
  - [0x6c648, asmtu, effect18]
  - [0x70658, asmtu, effect19]
  - [0x711a8, asmtu, effect20]
  - [0x782c0, asmtu, effect21]
  - [0x790e8, asmtu, effect22]
  - [0x7b588, asmtu, effect23]
  - [0x7dd98, asmtu, effect24]
  - [0x7ebd8, asmtu, effect25]
  - [0x80d88, asmtu, effect26]
  - [0x81368, asmtu, effect27]
  - [0x82868, asmtu, effect28]
  - [0x8d898, asmtu, effect29]
  - [0x8e1d0, asmtu, effect30]
  - [0x8eca0, asmtu, effect31]
  - [0x93ad8, asmtu, effect33]
  - [0x97168, asmtu, effect39]
  - [0x981b0, asmtu, effect40]
  - [0x989d0, asmtu, effect41]
  - [0x9d3a0, asmtu, effect42]
  - [0x9eea8, asmtu, effect43]
  - [0x9fab0, asmtu, effect49]
  - [0xa07d8, asmtu, effect74]
  - [0xa1258, asmtu, stage_effect00]
  - [0xa1960, asmtu, stage_effect01]
  - [0xa21e8, asmtu, stage_effect02]
  - [0xa26e8, asmtu, stage_effect03]
  - [0xa2cb8, asmtu, stage_effect04]
  - [0xa3460, asmtu, stage_effect05]
  - [0xa3e90, asmtu, stage_effect06]
  - [0xa4b70, asmtu, stage_effect07]
  - [0xa5568, asmtu, stage_effect08]
  - [0xa5d58, asmtu, stage_effect09]
  - [0xa65a0, asmtu, stage_effect10]
  - [0xa6a70, asmtu, stage_effect11]
  - [0xa7090, asmtu, stage_effect12]
  - [0xa78c8, asmtu, stage_effect13]
  - [0xa8f70, asmtu, stage_effect14]
  - [0xa96d0, asmtu, stage_effect15]
  - [0xaa1f8, asmtu, stage_effect16]
  - [0xaa578, asmtu, stage_effect17]
  - [0xaaa38, asmtu, stage_effect18]
  - [0xaaf08, asmtu, stage_effect19]
  - [0xabb70, asmtu, stage_effect20]
  - [0xac610, asmtu, stage_effect21]
  - [0xacf70, asmtu, stage_effect22]
  - [0xad810, asmtu, stage_effect23]
  - [0xae0b0, asmtu, stage_effect24]
  - [0xae908, asmtu, stage_effect25]
  - [0xaf178, asmtu, stage_effect26]
  - [0xafeb0, asmtu, stage_effect27]
  - [0xb0820, asmtu, stage_effect28]
  - [0xb0e08, asmtu, stage_effect29]
  - [0xb12b0, asmtu, stage_effect30]
  - [0xb1a90, asmtu, stage_effect32]
  - [0xb26d0, asmtu, stage_effect33]
  - [0xb2f00, asmtu, stage_effect35]
  - [0xb3b58, asmtu, stage_effect44]
  - [0xb40f8, asmtu, stage_effect45]
  - [0xb44b0, asmtu, stage_effect47]
  - [0xb49e0, asmtu, stage_effect48]
  - [0xb55d0, asmtu, stage_effect49]
  - [0xb5e78, pad]
  - [0xb5e80, .data, lb_event]
  - [0xb5fc8, .data, kitchen]
  - [0xb6e70, .data, training]
  - [0xb74d0, .data, farm_sys]
  - [0xb9f70, .data, effect_manager]
  - [0xba4a0, .data, hit_sub0]
  - [0xba4e8, .data, hitcheck]
  - [0xba598, .data, gamestage]
  - [0xcc130, .data, effect_base]
  - [0xcc1d0, .data, effect01]
  - [0xcc248, .data, effect02]
  - [0xcc310, .data, effect03]
  - [0xcd090, .data, effect04]
  - [0xcdca8, .data, effect05]
  - [0xceb20, .data, effect06]
  - [0xcfe90, .data, effect07]
  - [0xcffc0, .data, effect08]
  - [0xd0330, .data, effect09]
  - [0xd0808, .data, effect10]
  - [0xd09d0, .data, effect11]
  - [0xd0a10, .data, effect12]
  - [0xd0d10, .data, effect13]
  - [0xd1e70, .data, effect14]
  - [0xd2858, .data, effect15]
  - [0xd2ee8, .data, effect16]
  - [0xd3408, .data, effect17]
  - [0xd47d8, .data, effect18]
  - [0xd5c50, .data, effect19]
  - [0xd6038, .data, effect20]
  - [0xd90f8, .data, effect21]
  - [0xd9138, .data, effect22]
  - [0xd9220, .data, effect23]
  - [0xd9270, .data, effect24]
  - [0xd92e0, .data, effect25]
  - [0xda138, .data, effect26]
  - [0xda170, .data, effect27]
  - [0xda380, .data, effect28]
  - [0xdcc48, .data, effect29]
  - [0xdccb0, .data, effect30]
  - [0xdccf0, .data, effect31]
  - [0xdd538, .data, effect33]
  - [0xdd6b8, .data, effect39]
  - [0xdd7f0, .data, effect40]
  - [0xdd840, .data, effect41]
  - [0xdedc0, .data, effect42]
  - [0xdee48, .data, effect43]
  - [0xdee68, .data, effect49]
  - [0xdf198, .data, effect74]
  - [0xdf1c8, .data, stage_effect00]
  - [0xdf1f8, .data, stage_effect01]
  - [0xdf228, .data, stage_effect02]
  - [0xdf258, .data, stage_effect03]
  - [0xdf2a8, .data, stage_effect04]
  - [0xdf2d8, .data, stage_effect05]
  - [0xdf308, .data, stage_effect06]
  - [0xdf338, .data, stage_effect07]
  - [0xdf368, .data, stage_effect08]
  - [0xdf498, .data, stage_effect09]
  - [0xdf4c8, .data, stage_effect10]
  - [0xdf4f8, .data, stage_effect11]
  - [0xdf528, .data, stage_effect12]
  - [0xdf548, .data, stage_effect13]
  - [0xdf9f0, .data, stage_effect14]
  - [0xdfa20, .data, stage_effect15]
  - [0xdfa50, .data, stage_effect16]
  - [0xdfa80, .data, stage_effect17]
  - [0xdfab0, .data, stage_effect18]
  - [0xdfae0, .data, stage_effect19]
  - [0xdfb10, .data, stage_effect20]
  - [0xdfba0, .data, stage_effect21]
  - [0xdfbe0, .data, stage_effect22]
  - [0xdfc10, .data, stage_effect23]
  - [0xdfc50, .data, stage_effect24]
  - [0xdfc80, .data, stage_effect25]
  - [0xdfcc0, .data, stage_effect26]
  - [0xdfd08, .data, stage_effect27]
  - [0xdfd38, .data, stage_effect28]
  - [0xdfd68, .data, stage_effect29]
  - [0xdfd98, .data, stage_effect30]
  - [0xdfdc8, .data, stage_effect32]
  - [0xdfdf8, .data, stage_effect33]
  - [0xdfe38, .data, stage_effect35]
  - [0xdfe78, .data, stage_effect44]
  - [0xdfeb8, .data, stage_effect45]
  - [0xdfee8, .data, stage_effect47]
  - [0xdff18, .data, stage_effect48]
  - [0xdff58, .data, stage_effect49]
  - [0xdff98, pad]
  - [0xe0000, .rodata, lb_event]
  - [0xe0040, .rodata, kitchen]
  - [0xe00f0, .rodata, training]
  - [0xe02d8, .rodata, farm_sys]
  - [0xe0300, .rodata, effect_manager]
  - [0xe0398, .rodata, hitcheck]
  - [0xe05e8, .rodata, effect02]
  - [0xe0680, .rodata, effect04]
  - [0xe0778, .rodata, effect05]
  - [0xe0798, .rodata, effect06]
  - [0xe08c0, .rodata, effect07]
  - [0xe0938, .rodata, effect08]
  - [0xe0998, .rodata, effect12]
  - [0xe09b8, .rodata, effect13]
  - [0xe0d80, .rodata, effect14]
  - [0xe0f30, .rodata, effect15]
  - [0xe0ff0, .rodata, effect16]
  - [0xe1138, .rodata, effect17]
  - [0xe13e0, .rodata, effect18]
  - [0xe14d8, .rodata, effect20]
  - [0xe1840, .rodata, effect22] # fishing lure
  - [0xe1858, .rodata, effect23] # fish
  - [0xe18a0, .rodata, effect25]
  - [0xe19a0, .rodata, effect28]
  - [0xe1de0, .rodata, effect31]
  - [0xe1f70, .rodata, effect39]
  - [0xe2010, .rodata, effect41]
  - [0xe2200, .rodata, stage_effect05]
  - [0xe2218, .rodata, stage_effect22]
  - [0xe2230, .rodata, stage_effect35]
  - [0xe2248, .rodata, stage_effect48]
  - [0xe2280, .init, lb_event]
  - [0xe22a4, .init, kitchen]
  - [0xe22e0, .init, training]
  - [0xe2304, .init, farm_sys]
  - [0xe2340, .init, dialog]
  - [0xe2364, .init, effect_manager]
  - [0xe23a0, .init, hit_sub0]
  - [0xe23c4, .init, gamestage]
  - [0xe23f0, .ctor, lb_event]
  - [0xe23f4, .ctor, kitchen]
  - [0xe23f8, .ctor, training]
  - [0xe23fc, .ctor, farm_sys]
  - [0xe2400, .ctor, dialog]
  - [0xe2404, .ctor, effect_manager]
  - [0xe2408, .ctor, hit_sub0]
  - [0xe240c, .ctor, gamestage]
  - [0xe2410, pad]
  - {start: 0xe2480, type: .bss, vram: 0x09CF6700, name: lb_event}
  - {start: 0xe2480, type: .bss, vram: 0x09CF6720, name: kitchen}
  - {start: 0xe2480, type: .bss, vram: 0x09CF6820, name: training}
  - {start: 0xe2480, type: .bss, vram: 0x09CF6B50, name: farm_sys}
  - {start: 0xe2480, type: .bss, vram: 0x09CF6B78, name: dialog}
  - {start: 0xe2480, type: .bss, vram: 0x09CF6BB0, name: effect_manager}
  - {start: 0xe2480, type: .bss, vram: 0x09D146E8, name: hit_sub0}
  - {start: 0xe2480, type: .bss, vram: 0x09D14FE8, name: gamestage}
  - {start: 0xe2480, type: .bss, vram: 0x09D15008, name: effect10}
  - {start: 0xe2480, type: .bss, vram: 0x09D15018, name: effect15}
  - {start: 0xe2480, type: .bss, vram: 0x09D15038, name: effect42}
  - {start: 0xe2480, type: .bss, vram: 0x09D15080, name: effect49}
  type: code
  vram: 0x09C142C0
- - 0xe2480
sha1: 9a7178e83056754a8eaa89410632245877e452af
