name: stage166
options:
  add_set_gp_64: false
  asm_inc_header: |-
    .set noat
    .set noreorder
  asm_path: asm/stage1/stage166
  asset_path: assets/stage1/stage166
  auto_decompile_empty_functions: true
  base_path: ../..
  basename: stage166.ovl
  build_path: build
  compiler: MWCCPS2
  create_asm_dependencies: true
  create_undefined_funcs_auto: true
  create_undefined_syms_auto: true
  data_string_encoding: SHIFT_JIS
  data_string_guesser_level: 0
  disassemble_all: true
  extensions_path: tools/splat_ext
  find_file_boundaries: true
  global_vram_end: 0x09ffffff
  global_vram_start: 0x08000000
  gp_value: 0x089ceb50
  ld_bss_is_noload: true
  ld_generate_symbol_per_data_segment: true
  ld_script_path: build/config/stage1/stage166.ld
  make_full_disasm_for_code: true
  migrate_rodata_to_functions: true
  named_regs_for_c_funcs: false
  o_as_suffix: true
  pair_rodata_to_text: true
  platform: psp
  reloc_addrs_path:
  - config/stage1/stage166.reloc_addrs.txt
  rodata_string_guesser_level: 0
  section_order:
  - .text
  - .data
  - .rodata
  - .init
  - .ctor
  - .bss
  src_path: src/stage1/stage166
  string_encoding: SHIFT_JIS
  suggestion_rodata_section_start: true
  symbol_addrs_path:
  - config/stage1/stage166.symbol_addrs.txt
  symbol_name_format: stage166_$VRAM
  symbol_name_format_no_rom: $VRAM
  target_path: modules/stage1/stage166.ovl
  undefined_funcs_auto_path: build/config/stage1/stage166.undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/stage1/stage166.undefined_syms_auto.txt
segments:
- - 0
  - bin
  - omit_ovl_header
- align: 4
  bss_size: 0x480
  name: stage166
  start: 0x40
  subalign: 4
  subsegments:
  - [0x40, pad]
  - [0x80, asm, stage166]
  - [0x260, pad]
  - [0x280, data, stage166]
  - [0x680, init, stage166]
  - [0x6c0, ctor, stage166]
  - [0x6c4, pad]
  - [0x700, bss, stage166]
  type: code
  vram: 0x09d5dfc0
- - 0x700
sha1: 1e8e801f92df32097c7a0743a4956c490a03ebce
