#include "item_manager.hpp"
#include "common.h"

MixDefinition MIX_DEFINITIONS[172] = {
    { /* ItemId::POTION             + */ ItemId::HUSKBERRY,          /* = */ ItemId::RECOV_S_LV2,         MixRateId::_90_PERCENT,  MixQuantityId::_1,        0, 0,                                           0 },
    { /* ItemId::POTION             + */ ItemId::HONEY,              /* = */ ItemId::MEGA_POTION,         MixRateId::_90_PERCENT,  MixQuantityId::_1,        1, 0,                                           1 },
    { /* ItemId::NUTRIENTS          + */ ItemId::HONEY,              /* = */ ItemId::MEGA_NUTRIENTS,      MixRateId::_75_PERCENT,  MixQuantityId::_1,        2, 0,                                           2 },
    { /* ItemId::MEGA_NUTRIENTS     + */ ItemId::DRAGON_TOADSTOOL,   /* = */ ItemId::MAX_POTION,          MixRateId::_65_PERCENT,  MixQuantityId::_1,        3, 0,                                           3 },
    { /* ItemId::IMMUNIZER          + */ ItemId::POWER_SEED,         /* = */ ItemId::POWER_PILL,          MixRateId::_75_PERCENT,  MixQuantityId::_1,        4, 0,                                           4 },
    { /* ItemId::IMMUNIZER          + */ ItemId::ARMOR_SEED,         /* = */ ItemId::ARMOR_PILL,          MixRateId::_75_PERCENT,  MixQuantityId::_1,        5, 0,                                           5 },
    { /* ItemId::IMMUNIZER          + */ ItemId::KELBI_HORN,         /* = */ ItemId::ANCIENT_POTION,      MixRateId::_55_PERCENT,  MixQuantityId::_1,        6, 0,                                           6 },
    { /* ItemId::DEMONDRUG          + */ ItemId::PALE_EXTRACT,       /* = */ ItemId::MEGA_DEMONDRUG,      MixRateId::_55_PERCENT,  MixQuantityId::_1,        7, 0,                                           7 },
    { /* ItemId::MEGA_DEMONDRUG     + */ ItemId::MED_MONSTER_BONE,   /* = */ ItemId::DEMON_FLUTE,         MixRateId::_55_PERCENT,  MixQuantityId::_1,        8, 0,                                           8 },
    { /* ItemId::ARMORSKIN          + */ ItemId::PALE_EXTRACT,       /* = */ ItemId::MEGA_ARMORSKIN,      MixRateId::_55_PERCENT,  MixQuantityId::_1,        9, 0,                                           9 },
    { /* ItemId::MEGA_ARMORSKIN     + */ ItemId::MED_MONSTER_BONE,   /* = */ ItemId::ARMOR_FLUTE,         MixRateId::_55_PERCENT,  MixQuantityId::_1,       10, 0,                                          10 },
    { /* ItemId::CATALYST           + */ ItemId::RARE_STEAK,         /* = */ ItemId::POWER_JUICE,         MixRateId::_75_PERCENT,  MixQuantityId::_1,       11, 0,                                          11 },
    { /* ItemId::CATALYST           + */ ItemId::DRAGON_TOADSTOOL,   /* = */ ItemId::IMMUNIZER,           MixRateId::_75_PERCENT,  MixQuantityId::_1,       12, 0,                                          12 },
    { /* ItemId::CATALYST           + */ ItemId::POWER_SEED,         /* = */ ItemId::DEMONDRUG,           MixRateId::_65_PERCENT,  MixQuantityId::_1,       13, 0,                                          13 },
    { /* ItemId::CATALYST           + */ ItemId::ARMOR_SEED,         /* = */ ItemId::ARMORSKIN,           MixRateId::_65_PERCENT,  MixQuantityId::_1,       14, 0,                                          14 },
    { /* ItemId::GUNPOWDER          + */ ItemId::LARGE_BARREL,       /* = */ ItemId::LG_BARREL_BOMB,      MixRateId::_75_PERCENT,  MixQuantityId::_1,       15, MixFlag::BOMB,                              15 },
    { /* ItemId::GUNPOWDER          + */ ItemId::SCREAMER,           /* = */ ItemId::SONIC_BOMB,          MixRateId::_75_PERCENT,  MixQuantityId::_1,       16, MixFlag::BOMB,                              16 },
    { /* ItemId::LIFECRYSTALS       + */ ItemId::WYVERN_CLAW,        /* = */ ItemId::LIFEPOWDER,          MixRateId::_65_PERCENT,  MixQuantityId::_1,       17, 0,                                          17 },
    { /* ItemId::LIFEPOWDER         + */ ItemId::FLUTE,              /* = */ ItemId::HEALTH_FLUTE,        MixRateId::_65_PERCENT,  MixQuantityId::_1,       18, 0,                                          18 },
    { /* ItemId::POWERCHARM         + */ ItemId::LAO_SHANS_CLAW,     /* = */ ItemId::POWERTALON,          MixRateId::_100_PERCENT, MixQuantityId::_1,       19, MixFlag::REVEAL_ADD,                        19 },
    { /* ItemId::ARMORCHARM         + */ ItemId::LAO_SHANS_CLAW,     /* = */ ItemId::ARMORTALON,          MixRateId::_100_PERCENT, MixQuantityId::_1,       20, MixFlag::REVEAL_ADD,                        20 },
    { /* ItemId::TRANQUILIZER       + */ ItemId::THROWING_KNIFE,     /* = */ ItemId::TRANQ_THRWNG_KNF,    MixRateId::_65_PERCENT,  MixQuantityId::_1,       21, 0,                                          21 },
    { /* ItemId::TRANQUILIZER       + */ ItemId::BOMB_MATERIAL,      /* = */ ItemId::TRANQ_BOMB,          MixRateId::_75_PERCENT,  MixQuantityId::_1,       22, 0,                                          22 },
    { /* ItemId::TRANQUILIZER       + */ ItemId::SM_BONE_HUSK,       /* = */ ItemId::TRANQ_S,             MixRateId::_90_PERCENT,  MixQuantityId::_1,       23, 0,                                          23 },
    { /* ItemId::RAW_MEAT           + */ ItemId::SLEEP_HERB,         /* = */ ItemId::DRUGGED_MEAT,        MixRateId::_90_PERCENT,  MixQuantityId::_1,       24, MixFlag::TRAP,                              24 },
    { /* ItemId::RAW_MEAT           + */ ItemId::PARASHROOM,         /* = */ ItemId::TAINTED_MEAT,        MixRateId::_90_PERCENT,  MixQuantityId::_1,       25, MixFlag::TRAP,                              25 },
    { /* ItemId::RAW_MEAT           + */ ItemId::TOADSTOOL,          /* = */ ItemId::POISONED_MEAT,       MixRateId::_90_PERCENT,  MixQuantityId::_1,       26, MixFlag::TRAP,                              26 },
    { /* ItemId::WELL-DONE_STEAK    + */ ItemId::HOT_PEPPER,         /* = */ ItemId::HOT_MEAT,            MixRateId::_95_PERCENT,  MixQuantityId::_1,       27, 0,                                          27 },
    { /* ItemId::WELL-DONE_STEAK    + */ ItemId::ICE_CRYSTAL,        /* = */ ItemId::COLD_MEAT,           MixRateId::_95_PERCENT,  MixQuantityId::_1,       28, 0,                                          28 },
    { /* ItemId::WELL-DONE_STEAK    + */ ItemId::POWER_EXTRACT,      /* = */ ItemId::MEGA_JUICE,          MixRateId::_65_PERCENT,  MixQuantityId::_1,       29, 0,                                          29 },
    { /* ItemId::BURNT_MEAT         + */ ItemId::INSECT_HUSK,        /* = */ ItemId::RAW_MEAT,            MixRateId::_95_PERCENT,  MixQuantityId::_1,       30, MixFlag::ALCHEMY,                           30 },
    { /* ItemId::BURNT_FISH         + */ ItemId::SUNSET_HERB,        /* = */ ItemId::RARE_FISH,           MixRateId::_90_PERCENT,  MixQuantityId::_1,       31, MixFlag::ALCHEMY,                           31 },
    { /* ItemId::THROWING_KNIFE     + */ ItemId::SLEEP_HERB,         /* = */ ItemId::SLEEPING_THR_KNF,    MixRateId::_90_PERCENT,  MixQuantityId::_1,       32, 0,                                          32 },
    { /* ItemId::THROWING_KNIFE     + */ ItemId::PARASHROOM,         /* = */ ItemId::PARALYZE_THR_KNF,    MixRateId::_90_PERCENT,  MixQuantityId::_1,       33, 0,                                          33 },
    { /* ItemId::THROWING_KNIFE     + */ ItemId::TOADSTOOL,          /* = */ ItemId::POISON_THRW_KNF,     MixRateId::_90_PERCENT,  MixQuantityId::_1,       34, 0,                                          34 },
    { /* ItemId::BOMB_MATERIAL      + */ ItemId::DUNG,               /* = */ ItemId::DUNG_BOMB,           MixRateId::_75_PERCENT,  MixQuantityId::_1,       35, 0,                                          35 },
    { /* ItemId::BOMB_MATERIAL      + */ ItemId::SUNSET_HERB,        /* = */ ItemId::DEODORANT,           MixRateId::_95_PERCENT,  MixQuantityId::_1,       36, 0,                                          36 },
    { /* ItemId::BOMB_MATERIAL      + */ ItemId::IVY,                /* = */ ItemId::SMOKE_BOMB,          MixRateId::_75_PERCENT,  MixQuantityId::_1,       37, 0,                                          37 },
    { /* ItemId::BOMB_MATERIAL      + */ ItemId::TOADSTOOL,          /* = */ ItemId::POISON_SMOKE_BMB,    MixRateId::_75_PERCENT,  MixQuantityId::_1,       38, 0,                                          38 },
    { /* ItemId::BOMB_MATERIAL      + */ ItemId::EXCITESHROOM,       /* = */ ItemId::FARCASTER,           MixRateId::_95_PERCENT,  MixQuantityId::_1,       39, 0,                                          39 },
    { /* ItemId::BOMB_MATERIAL      + */ ItemId::FLASHBUG,           /* = */ ItemId::FLASH_BOMB,          MixRateId::_75_PERCENT,  MixQuantityId::_1,       40, 0,                                          40 },
    { /* ItemId::SPIDERWEB          + */ ItemId::IVY,                /* = */ ItemId::NET,                 MixRateId::_90_PERCENT,  MixQuantityId::_1,       41, MixFlag::TRAP,                              41 },
    { /* ItemId::NET                + */ ItemId::TRAP_TOOL,          /* = */ ItemId::PITFALL_TRAP,        MixRateId::_75_PERCENT,  MixQuantityId::_1,       42, MixFlag::TRAP,                              42 },
    { /* ItemId::NET                + */ ItemId::SM_MONSTER_BONE,    /* = */ ItemId::BUGNET,              MixRateId::_75_PERCENT,  MixQuantityId::_1,       43, 0,                                          43 },
    { /* ItemId::NET                + */ ItemId::MED_MONSTER_BONE,   /* = */ ItemId::MEGA_BUGNET,         MixRateId::_95_PERCENT,  MixQuantityId::_1,       44, 0,                                          44 },
    { /* ItemId::NET                + */ ItemId::MYSTERY_BONE,       /* = */ ItemId::OLD_BUGNET,          MixRateId::_95_PERCENT,  MixQuantityId::_1,       45, 0,                                          45 },
    { /* ItemId::TRAP_TOOL          + */ ItemId::GENPREY_FANG,       /* = */ ItemId::SHOCK_TRAP,          MixRateId::_90_PERCENT,  MixQuantityId::_1,       46, MixFlag::TRAP,                              46 },
    { /* ItemId::SMALL_BARREL       + */ ItemId::FIRE_HERB,          /* = */ ItemId::SM_BARREL_BOMB,      MixRateId::_90_PERCENT,  MixQuantityId::_1,       47, MixFlag::BOMB,                              47 },
    { /* ItemId::SM_BARREL-BOMB     + */ ItemId::BURST_ARROWANA,     /* = */ ItemId::SM_BARREL_BOMB_PLUS, MixRateId::_90_PERCENT,  MixQuantityId::_1,       48, MixFlag::BOMB,                              48 },
    { /* ItemId::SM_BARREL-BOMB     + */ ItemId::VESPOID_WING,       /* = */ ItemId::BOUNCE_BOMB,         MixRateId::_75_PERCENT,  MixQuantityId::_1,       49, MixFlag::BOMB,                              49 },
    { /* ItemId::LG_BARREL-BOMB     + */ ItemId::SCATTERFISH,        /* = */ ItemId::LG_BARREL_BOMB_PLUS, MixRateId::_75_PERCENT,  MixQuantityId::_1,       50, MixFlag::BOMB,                              50 },
    { /* ItemId::BOUNCE_BOMB        + */ ItemId::BOMB_ARROWANA,      /* = */ ItemId::BOUNCE_BOMB_PLUS,    MixRateId::_75_PERCENT,  MixQuantityId::_1,       51, MixFlag::BOMB,                              51 },
    { /* ItemId::HUSKBERRY          + */ ItemId::HERB,               /* = */ ItemId::RECOV_S_LV1,         MixRateId::_90_PERCENT,  MixQuantityId::_1,       52, 0,                                          52 },
    { /* ItemId::HUSKBERRY          + */ ItemId::FIRE_HERB,          /* = */ ItemId::FLAMING_S,           MixRateId::_90_PERCENT,  MixQuantityId::_1,       53, 0,                                          53 },
    { /* ItemId::HUSKBERRY          + */ ItemId::SLEEP_HERB,         /* = */ ItemId::SLEEP_S_LV1,         MixRateId::_90_PERCENT,  MixQuantityId::_1,       54, 0,                                          54 },
    { /* ItemId::HUSKBERRY          + */ ItemId::PARASHROOM,         /* = */ ItemId::PARA_S_LV1,          MixRateId::_90_PERCENT,  MixQuantityId::_1,       55, 0,                                          55 },
    { /* ItemId::HUSKBERRY          + */ ItemId::TOADSTOOL,          /* = */ ItemId::POISON_S_LV1,        MixRateId::_90_PERCENT,  MixQuantityId::_1,       56, 0,                                          56 },
    { /* ItemId::HUSKBERRY          + */ ItemId::PAINTBERRY,         /* = */ ItemId::PAINT_S,             MixRateId::_90_PERCENT,  MixQuantityId::_1,       57, 0,                                          57 },
    { /* ItemId::HUSKBERRY          + */ ItemId::POWER_SEED,         /* = */ ItemId::DEMON_S,             MixRateId::_75_PERCENT,  MixQuantityId::_1,       58, 0,                                          58 },
    { /* ItemId::HUSKBERRY          + */ ItemId::ARMOR_SEED,         /* = */ ItemId::ARMOR_S,             MixRateId::_75_PERCENT,  MixQuantityId::_1,       59, 0,                                          59 },
    { /* ItemId::HUSKBERRY          + */ ItemId::SCATTERNUT,         /* = */ ItemId::PELLET_S_LV1,        MixRateId::_90_PERCENT,  MixQuantityId::_1_TO_3,  60, 0,                                          60 },
    { /* ItemId::HUSKBERRY          + */ ItemId::NEEDLEBERRY,        /* = */ ItemId::NORMAL_S_LV2,        MixRateId::_95_PERCENT,  MixQuantityId::_2_TO_4,  61, 0,                                          61 },
    { /* ItemId::HUSKBERRY          + */ ItemId::BOMBERRY,           /* = */ ItemId::CLUST_S_LV1,         MixRateId::_90_PERCENT,  MixQuantityId::_1,       62, 0,                                          62 },
    { /* ItemId::HUSKBERRY          + */ ItemId::IRON_ORE,           /* = */ ItemId::HUSKBERRY,           MixRateId::_75_PERCENT,  MixQuantityId::_5,       63, MixFlag::ALCHEMY,                           63 },
    { /* ItemId::HUSKBERRY          + */ ItemId::ICE_CRYSTAL,        /* = */ ItemId::FREEZE_S,            MixRateId::_75_PERCENT,  MixQuantityId::_1_TO_3,  64, 0,                                          64 },
    { /* ItemId::HUSKBERRY          + */ ItemId::KNIFE_MACKEREL,     /* = */ ItemId::WATER_S,             MixRateId::_75_PERCENT,  MixQuantityId::_1_TO_3,  65, 0,                                          65 },
    { /* ItemId::HUSKBERRY          + */ ItemId::PIN_TUNA,           /* = */ ItemId::PIERCE_S_LV2,        MixRateId::_75_PERCENT,  MixQuantityId::_1_TO_3,  66, 0,                                          66 },
    { /* ItemId::HUSKBERRY          + */ ItemId::RUMBLEFISH,         /* = */ ItemId::NORMAL_S_LV3,        MixRateId::_95_PERCENT,  MixQuantityId::_2_TO_4,  67, 0,                                          67 },
    { /* ItemId::HUSKBERRY          + */ ItemId::BURST_ARROWANA,     /* = */ ItemId::CRAG_S_LV1,          MixRateId::_90_PERCENT,  MixQuantityId::_1,       68, 0,                                          68 },
    { /* ItemId::HUSKBERRY          + */ ItemId::FLASHBUG,           /* = */ ItemId::THUNDER_S,           MixRateId::_75_PERCENT,  MixQuantityId::_2_TO_4,  69, 0,                                          69 },
    { /* ItemId::HUSKBERRY          + */ ItemId::WYVERN_FANG,        /* = */ ItemId::PELLET_S_LV2,        MixRateId::_75_PERCENT,  MixQuantityId::_1_TO_3,  70, 0,                                          70 },
    { /* ItemId::HUSKBERRY          + */ ItemId::VELOCIPREY_FANG,    /* = */ ItemId::PIERCE_S_LV1,        MixRateId::_90_PERCENT,  MixQuantityId::_1_TO_3,  71, 0,                                          71 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::WHETSTONE,          /* = */ ItemId::EMPTY_BOTTLE,        MixRateId::_85_PERCENT,  MixQuantityId::_1_TO_2,  72, 0,                                          72 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::SLEEPYFISH,         /* = */ ItemId::SLEEP_S_LV2,         MixRateId::_75_PERCENT,  MixQuantityId::_1,       73, 0,                                          73 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::PIN_TUNA,           /* = */ ItemId::PIERCE_S_LV3,        MixRateId::_75_PERCENT,  MixQuantityId::_1_TO_2,  74, 0,                                          74 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::BURST_ARROWANA,     /* = */ ItemId::CRAG_S_LV2,          MixRateId::_90_PERCENT,  MixQuantityId::_1,       75, 0,                                          75 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::WYVERN_FANG,        /* = */ ItemId::PELLET_S_LV3,        MixRateId::_75_PERCENT,  MixQuantityId::_1_TO_3,  76, 0,                                          76 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::WYVERN_CLAW,        /* = */ ItemId::CLUST_S_LV2,         MixRateId::_75_PERCENT,  MixQuantityId::_1,       77, 0,                                          77 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::GENPREY_FANG,       /* = */ ItemId::PARA_S_LV2,          MixRateId::_90_PERCENT,  MixQuantityId::_1,       78, 0,                                          78 },
    { /* ItemId::SM_BONE_HUSK       + */ ItemId::IOPREY_FANG,        /* = */ ItemId::POISON_S_LV2,        MixRateId::_75_PERCENT,  MixQuantityId::_1,       79, 0,                                          79 },
    { /* ItemId::LG_BONE_HUSK       + */ ItemId::DRAGON_SEED,        /* = */ ItemId::DRAGON_S,            MixRateId::_75_PERCENT,  MixQuantityId::_1,       80, 0,                                          80 },
    { /* ItemId::LG_BONE_HUSK       + */ ItemId::SCATTERFISH,        /* = */ ItemId::CLUST_S_LV3,         MixRateId::_75_PERCENT,  MixQuantityId::_1,       81, 0,                                          81 },
    { /* ItemId::LG_BONE_HUSK       + */ ItemId::BOMB_ARROWANA,      /* = */ ItemId::CRAG_S_LV3,          MixRateId::_95_PERCENT,  MixQuantityId::_1,       82, 0,                                          82 },
    { /* ItemId::EMPTY_BOTTLE       + */ ItemId::SLEEP_HERB,         /* = */ ItemId::SLEEP_COATING,       MixRateId::_90_PERCENT,  MixQuantityId::_1_TO_2,  83, 0,                                          83 },
    { /* ItemId::EMPTY_BOTTLE       + */ ItemId::NITROSHROOM,        /* = */ ItemId::POWER_COATING,       MixRateId::_85_PERCENT,  MixQuantityId::_1_TO_2,  84, 0,                                          84 },
    { /* ItemId::EMPTY_BOTTLE       + */ ItemId::PARASHROOM,         /* = */ ItemId::PARALYSIS_COATING,   MixRateId::_85_PERCENT,  MixQuantityId::_1_TO_2,  85, 0,                                          85 },
    { /* ItemId::EMPTY_BOTTLE       + */ ItemId::TOADSTOOL,          /* = */ ItemId::POISON_COATING,      MixRateId::_90_PERCENT,  MixQuantityId::_1_TO_2,  86, 0,                                          86 },
    { /* ItemId::EMPTY_BOTTLE       + */ ItemId::PAINTBERRY,         /* = */ ItemId::PAINT_COATING,       MixRateId::_90_PERCENT,  MixQuantityId::_1_TO_2,  87, 0,                                         255 },
    { /* ItemId::EMPTY_BOTTLE       + */ ItemId::KNIFE_MACKEREL,     /* = */ ItemId::CLOSE_RNG_COATING,   MixRateId::_85_PERCENT,  MixQuantityId::_1_TO_2,  88, 0,                                         255 },
    { /* ItemId::CRICKET            + */ ItemId::BUGHOPPER,          /* = */ ItemId::ARROWANA_BAIT,       MixRateId::_95_PERCENT,  MixQuantityId::_1,       89, 0,                                          87 },
    { /* ItemId::WORM               + */ ItemId::YAMBUG,             /* = */ ItemId::TUNA_BAIT,           MixRateId::_95_PERCENT,  MixQuantityId::_1,       90, 0,                                          88 },
    { /* ItemId::FIREFLY            + */ ItemId::SPECIAL_MUSHROOM,   /* = */ ItemId::HONEY,               MixRateId::_90_PERCENT,  MixQuantityId::_1,       91, MixFlag::ALCHEMY,                           89 },
    { /* ItemId::FIREFLY            + */ ItemId::SNAKEBEE_LARVA,     /* = */ ItemId::GOLDENFISH_BAIT,     MixRateId::_90_PERCENT,  MixQuantityId::_1,       92, 0,                                          90 },
    { /* ItemId::FROG               + */ ItemId::FLUTE,              /* = */ ItemId::SCREAMER,            MixRateId::_75_PERCENT,  MixQuantityId::_1,       93, MixFlag::ALCHEMY,                           91 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::DISK_STONE,         /* = */ ItemId::DISK_STONE,          MixRateId::_100_PERCENT, MixQuantityId::_5,       94, 0,                                          92 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::IRON_ORE,           /* = */ ItemId::IRON_ORE,            MixRateId::_100_PERCENT, MixQuantityId::_5,       95, 0,                                          93 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::EARTH_CRYSTAL,      /* = */ ItemId::EARTH_CRYSTAL,       MixRateId::_100_PERCENT, MixQuantityId::_3,       96, MixFlag::REVEAL_ADD,                        94 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::MACHALITE_ORE,      /* = */ ItemId::MACHALITE_ORE,       MixRateId::_100_PERCENT, MixQuantityId::_3,       97, MixFlag::REVEAL_ADD,                        95 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::DRAGONITE_ORE,      /* = */ ItemId::DRAGONITE_ORE,       MixRateId::_100_PERCENT, MixQuantityId::_3,       98, MixFlag::REVEAL_ADD,                        96 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::CARBALITE_ORE,      /* = */ ItemId::CARBALITE_ORE,       MixRateId::_100_PERCENT, MixQuantityId::_2,       99, MixFlag::REVEAL_ADD,                        97 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::ELTALITE_ORE,       /* = */ ItemId::ELTALITE_ORE,        MixRateId::_100_PERCENT, MixQuantityId::_2,      100, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::UNION_ORE,          /* = */ ItemId::UNION_ORE,           MixRateId::_100_PERCENT, MixQuantityId::_2,      101, MixFlag::REVEAL_ADD,                        98 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::MELLANJE_ORE,       /* = */ ItemId::MELLANJE_ORE,        MixRateId::_100_PERCENT, MixQuantityId::_2,      102, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::FIRESTONE,          /* = */ ItemId::FIRESTONE,           MixRateId::_100_PERCENT, MixQuantityId::_2,      103, MixFlag::REVEAL_ADD,                        99 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::FIRECELL_STONE,     /* = */ ItemId::FIRECELL_STONE,      MixRateId::_100_PERCENT, MixQuantityId::_2,      104, MixFlag::REVEAL_ADD,                       100 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::LIGHTCRYSTAL,       /* = */ ItemId::LIGHTCRYSTAL,        MixRateId::_100_PERCENT, MixQuantityId::_2,      105, MixFlag::REVEAL_ADD,                       101 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::NOVACRYSTAL,        /* = */ ItemId::NOVACRYSTAL,         MixRateId::_100_PERCENT, MixQuantityId::_2,      106, MixFlag::REVEAL_ADD,                       102 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::PURECRYSTAL,        /* = */ ItemId::PURECRYSTAL,         MixRateId::_100_PERCENT, MixQuantityId::_2,      107, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::CARPENTERBUG,       /* = */ ItemId::CARPENTERBUG,        MixRateId::_100_PERCENT, MixQuantityId::_5,      108, 0,                                         103 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::KING_SCARAB,        /* = */ ItemId::KING_SCARAB,         MixRateId::_100_PERCENT, MixQuantityId::_3,      109, MixFlag::REVEAL_ADD,                       104 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::EMPEROR_CRICKET,    /* = */ ItemId::EMPEROR_CRICKET,     MixRateId::_100_PERCENT, MixQuantityId::_2,      110, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::KILLER_BEETLE,      /* = */ ItemId::KILLER_BEETLE,       MixRateId::_100_PERCENT, MixQuantityId::_3,      111, MixFlag::REVEAL_ADD,                       105 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::HERCUDROME,         /* = */ ItemId::HERCUDROME,          MixRateId::_100_PERCENT, MixQuantityId::_3,      112, MixFlag::REVEAL_ADD,                       106 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::RARE_SCARAB,        /* = */ ItemId::RARE_SCARAB,         MixRateId::_100_PERCENT, MixQuantityId::_2,      113, MixFlag::REVEAL_ADD,                       107 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::PHANTOM_BUTTERFLY,  /* = */ ItemId::PHANTOM_BUTTERFLY,   MixRateId::_100_PERCENT, MixQuantityId::_2,      114, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::MONSTER_BONE_PLUS,  /* = */ ItemId::MONSTER_BONE_PLUS,   MixRateId::_100_PERCENT, MixQuantityId::_3,      115, MixFlag::REVEAL_ADD,                       108 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::HRD_MONSTER_BONE,   /* = */ ItemId::HRD_MONSTER_BONE,    MixRateId::_100_PERCENT, MixQuantityId::_2,      116, MixFlag::REVEAL_ADD,                       109 },
    { /* ItemId::EXPAND_PICKAXE     + */ ItemId::HVY_MONSTER_BONE,   /* = */ ItemId::HVY_MONSTER_BONE,    MixRateId::_100_PERCENT, MixQuantityId::_2,      117, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::WHETSTONE          + */ ItemId::SM_MONSTER_BONE,    /* = */ ItemId::BOOMERANG,           MixRateId::_90_PERCENT,  MixQuantityId::_1,      118, 0,                                         110 },
    { /* ItemId::GARBAGE            + */ ItemId::HOT_PEPPER,         /* = */ ItemId::FIRE_HERB,           MixRateId::_90_PERCENT,  MixQuantityId::_1,      119, MixFlag::ALCHEMY,                          111 },
    { /* ItemId::FLUTE              + */ ItemId::ANTISEPTIC_STONE,   /* = */ ItemId::ANTIDOTE_FLUTE,      MixRateId::_65_PERCENT,  MixQuantityId::_1,      120, 0,                                         112 },
    { /* ItemId::HONEY              + */ ItemId::SUNSET_HERB,        /* = */ ItemId::ENERGY_DRINK,        MixRateId::_65_PERCENT,  MixQuantityId::_1,      121, 0,                                         113 },
    { /* ItemId::HONEY              + */ ItemId::BITTERBUG,          /* = */ ItemId::CATALYST,            MixRateId::_75_PERCENT,  MixQuantityId::_1,      122, 0,                                         114 },
    { /* ItemId::HERB               + */ ItemId::BLUE_MUSHROOM,      /* = */ ItemId::POTION,              MixRateId::_95_PERCENT,  MixQuantityId::_1,      123, 0,                                         115 },
    { /* ItemId::ANTIDOTE_HERB      + */ ItemId::BLUE_MUSHROOM,      /* = */ ItemId::ANTIDOTE,            MixRateId::_95_PERCENT,  MixQuantityId::_1,      124, 0,                                         116 },
    { /* ItemId::ANTIDOTE_HERB      + */ ItemId::TOADSTOOL,          /* = */ ItemId::BLUE_MUSHROOM,       MixRateId::_95_PERCENT,  MixQuantityId::_1,      125, MixFlag::ALCHEMY,                          117 },
    { /* ItemId::ANTIDOTE_HERB      + */ ItemId::SLEEPYFISH,         /* = */ ItemId::SUSHIFISH,           MixRateId::_75_PERCENT,  MixQuantityId::_1,      126, MixFlag::ALCHEMY,                          118 },
    { /* ItemId::FIRE_HERB          + */ ItemId::NITROSHROOM,        /* = */ ItemId::GUNPOWDER,           MixRateId::_95_PERCENT,  MixQuantityId::_1,      127, MixFlag::BOMB,                             119 },
    { /* ItemId::FIRE_HERB          + */ ItemId::RUMBLEFISH,         /* = */ ItemId::THAWING_AGENT,       MixRateId::_95_PERCENT,  MixQuantityId::_1,      128, 0,                                         120 },
    { /* ItemId::IVY                + */ ItemId::MED_MONSTER_BONE,   /* = */ ItemId::LARGE_BARREL,        MixRateId::_65_PERCENT,  MixQuantityId::_1,      129, MixFlag::ALCHEMY,                          121 },
    { /* ItemId::SLEEP_HERB         + */ ItemId::PARASHROOM,         /* = */ ItemId::TRANQUILIZER,        MixRateId::_65_PERCENT,  MixQuantityId::_1,      130, 0,                                         122 },
    { /* ItemId::SAP_PLANT          + */ ItemId::PAINTBERRY,         /* = */ ItemId::PAINTBALL,           MixRateId::_95_PERCENT,  MixQuantityId::_1,      131, 0,                                         123 },
    { /* ItemId::SAP_PLANT          + */ ItemId::STONE,              /* = */ ItemId::BOMB_MATERIAL,       MixRateId::_95_PERCENT,  MixQuantityId::_2,      132, 0,                                         124 },
    { /* ItemId::SAP_PLANT          + */ ItemId::INSECT_HUSK,        /* = */ ItemId::HERB,                MixRateId::_95_PERCENT,  MixQuantityId::_1,      133, MixFlag::ALCHEMY,                          125 },
    { /* ItemId::SAP_PLANT          + */ ItemId::SM_MONSTER_BONE,    /* = */ ItemId::SMALL_BARREL,        MixRateId::_75_PERCENT,  MixQuantityId::_1,      134, MixFlag::ALCHEMY,                          126 },
    { /* ItemId::CACTUS_FLOWER      + */ ItemId::BITTERBUG,          /* = */ ItemId::HERBAL_MEDICINE,     MixRateId::_90_PERCENT,  MixQuantityId::_1,      135, 0,                                         127 },
    { /* ItemId::CACTUS_FLOWER      + */ ItemId::THUNDERBUG,         /* = */ ItemId::PSYCHOSERUM,         MixRateId::_75_PERCENT,  MixQuantityId::_1,      136, MixFlag::ALCHEMY,                          128 },
    { /* ItemId::HOT_PEPPER         + */ ItemId::SPECIAL_MUSHROOM,   /* = */ ItemId::SPICY_MUSHROOM,      MixRateId::_85_PERCENT,  MixQuantityId::_1,      137, 0,                                         129 },
    { /* ItemId::HOT_PEPPER         + */ ItemId::BITTERBUG,          /* = */ ItemId::HOT_DRINK,           MixRateId::_95_PERCENT,  MixQuantityId::_1,      138, 0,                                         130 },
    { /* ItemId::BLUE_MUSHROOM      + */ ItemId::GODBUG,             /* = */ ItemId::NUTRIENTS,           MixRateId::_90_PERCENT,  MixQuantityId::_1,      139, 0,                                         131 },
    { /* ItemId::DRAGON_SEED        + */ ItemId::PISCINE_LIVER,      /* = */ ItemId::POWER_EXTRACT,       MixRateId::_65_PERCENT,  MixQuantityId::_1,      140, MixFlag::ALCHEMY,                          132 },
    { /* ItemId::NEEDLEBERRY        + */ ItemId::EARTH_CRYSTAL,      /* = */ ItemId::NEEDLEBERRY,         MixRateId::_75_PERCENT,  MixQuantityId::_5,      141, MixFlag::ALCHEMY,                          133 },
    { /* ItemId::NEEDLEBERRY        + */ ItemId::GIAPREY_HIDE,       /* = */ ItemId::ARMOR_SEED,          MixRateId::_65_PERCENT,  MixQuantityId::_1,      142, MixFlag::ALCHEMY,                          134 },
    { /* ItemId::BOMBERRY           + */ ItemId::VELOCIPREY_HIDE,    /* = */ ItemId::POWER_SEED,          MixRateId::_65_PERCENT,  MixQuantityId::_1,      143, MixFlag::ALCHEMY,                          135 },
    { /* ItemId::TROPICAL_BERRY     + */ ItemId::ICE_CRYSTAL,        /* = */ ItemId::FROZEN_BERRY,        MixRateId::_85_PERCENT,  MixQuantityId::_1,      144, 0,                                         136 },
    { /* ItemId::STONE              + */ ItemId::BONE,               /* = */ ItemId::OLD_PICKAXE,         MixRateId::_95_PERCENT,  MixQuantityId::_1,      145, 0,                                         137 },
    { /* ItemId::IRON_ORE           + */ ItemId::BONE,               /* = */ ItemId::IRON_PICKAXE,        MixRateId::_75_PERCENT,  MixQuantityId::_1,      146, 0,                                         138 },
    { /* ItemId::EARTH_CRYSTAL      + */ ItemId::BITTERBUG,          /* = */ ItemId::ANTISEPTIC_STONE,    MixRateId::_75_PERCENT,  MixQuantityId::_1,      147, 0,                                         139 },
    { /* ItemId::MACHALITE_ORE      + */ ItemId::ARMOR_STONE,        /* = */ ItemId::ARMOR_SPHERE,        MixRateId::_100_PERCENT, MixQuantityId::_1,      148, 0,                                         140 },
    { /* ItemId::MACHALITE_ORE      + */ ItemId::BONE,               /* = */ ItemId::MEGA_PICKAXE,        MixRateId::_95_PERCENT,  MixQuantityId::_1,      149, 0,                                         141 },
    { /* ItemId::DRAGONITE_ORE      + */ ItemId::ARMOR_STONE,        /* = */ ItemId::ARMOR_SPHERE_PLUS,   MixRateId::_100_PERCENT, MixQuantityId::_1,      150, MixFlag::REVEAL_SUM,                       142 },
    { /* ItemId::CARBALITE_ORE      + */ ItemId::ARMOR_STONE,        /* = */ ItemId::HRD_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      151, MixFlag::REVEAL_SUM,                       143 },
    { /* ItemId::ELTALITE_ORE       + */ ItemId::ARMOR_STONE,        /* = */ ItemId::RYL_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      152, MixFlag::REVEAL_SUM,                       255 },
    { /* ItemId::MELLANJE_ORE       + */ ItemId::ARMOR_STONE,        /* = */ ItemId::TRU_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      153, MixFlag::REVEAL_SUM,                       255 },
    { /* ItemId::PURECRYSTAL        + */ ItemId::ARMOR_STONE,        /* = */ ItemId::HVY_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      154, MixFlag::REVEAL_SUM,                       255 },
    { /* ItemId::ICE_CRYSTAL        + */ ItemId::BITTERBUG,          /* = */ ItemId::COOL_DRINK,          MixRateId::_95_PERCENT,  MixQuantityId::_1,      155, 0,                                         114 },
    { /* ItemId::ICE_CRYSTAL        + */ ItemId::SLEEP_SAC,          /* = */ ItemId::MONSTER_FLUID,       MixRateId::_55_PERCENT,  MixQuantityId::_1,      156, MixFlag::ALCHEMY,                          145 },
    { /* ItemId::ARMOR_STONE        + */ ItemId::KING_SCARAB,        /* = */ ItemId::HRD_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      157, MixFlag::REVEAL_ADD,                       146 },
    { /* ItemId::ARMOR_STONE        + */ ItemId::EMPEROR_CRICKET,    /* = */ ItemId::RYL_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      158, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::ARMOR_STONE        + */ ItemId::KILLER_BEETLE,      /* = */ ItemId::ARMOR_SPHERE,        MixRateId::_100_PERCENT, MixQuantityId::_1,      159, 0,                                         147 },
    { /* ItemId::ARMOR_STONE        + */ ItemId::HERCUDROME,         /* = */ ItemId::ARMOR_SPHERE_PLUS,   MixRateId::_100_PERCENT, MixQuantityId::_1,      160, MixFlag::REVEAL_ADD,                       148 },
    { /* ItemId::ARMOR_STONE        + */ ItemId::PHANTOM_BUTTERFLY,  /* = */ ItemId::TRU_ARMOR_SPHERE,    MixRateId::_100_PERCENT, MixQuantityId::_1,      161, MixFlag::REVEAL_ADD,                       255 },
    { /* ItemId::BURST_ARROWANA     + */ ItemId::THUNDERBUG,         /* = */ ItemId::LIGHTNING_ROD,       MixRateId::_75_PERCENT,  MixQuantityId::_1,      162, MixFlag::BOMB,                             149 },
    { /* ItemId::GODBUG             + */ ItemId::WYVERN_FANG,        /* = */ ItemId::LIFECRYSTALS,        MixRateId::_90_PERCENT,  MixQuantityId::_1,      163, 0,                                         150 },
    { /* ItemId::THUNDERBUG         + */ ItemId::VELOCIPREY_HIDE,    /* = */ ItemId::RARE_STEAK,          MixRateId::_90_PERCENT,  MixQuantityId::_1,      164, MixFlag::ALCHEMY,                          151 },
    { /* ItemId::BLNGO_BLZRD_BALL   + */ ItemId::BLNGO_FLRRY_BALL,   /* = */ ItemId::POKKE_SNOWMAN,       MixRateId::_100_PERCENT, MixQuantityId::_1,      165, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 152 },
    { /* ItemId::INFERIOR_FLYN_CRN  + */ ItemId::FLYN_CRWN_FRGMNT,   /* = */ ItemId::FELYNE_CROWN,        MixRateId::_100_PERCENT, MixQuantityId::_1,      166, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 153 },
    { /* ItemId::HNDLELSS_GLD_BLD   + */ ItemId::GLD_BLADELESS_HNDL, /* = */ ItemId::GLD_FLYN_JEWEL_SWD,  MixRateId::_100_PERCENT, MixQuantityId::_1,      167, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 154 },
    { /* ItemId::BTTMLSS_OLD_VASE   + */ ItemId::OLD_VASE_BOTTOM,    /* = */ ItemId::DYNASTY_VASE,        MixRateId::_100_PERCENT, MixQuantityId::_1,      168, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 155 },
    { /* ItemId::HOLED_SHAKA_MASK   + */ ItemId::SHAKALAKA_STONE,    /* = */ ItemId::MYSTERIOUS_MASK,     MixRateId::_100_PERCENT, MixQuantityId::_1,      169, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 156 },
    { /* ItemId::TORN_OLD_BOOK      + */ ItemId::OLD_BOOK_SCRAP,     /* = */ ItemId::ELDR_DRGN_RFRNC,     MixRateId::_100_PERCENT, MixQuantityId::_1,      170, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 157 },
    { /* ItemId::TAILLESS_CAT_STATU + */ ItemId::BROKEN_STONE_TAIL,  /* = */ ItemId::ANCNT_CAT_KING_STAT, MixRateId::_100_PERCENT, MixQuantityId::_1,      171, MixFlag::REVEAL_SUM | MixFlag::REVEAL_ADD, 255 },
};

MixIndexEntry MIX_INDEX[1261] = {
    [ ItemId::POTION             ] = {  2,   0, },
    [ ItemId::NUTRIENTS          ] = {  1,   2, },
    [ ItemId::MEGA_NUTRIENTS     ] = {  1,   3, },
    [ ItemId::IMMUNIZER          ] = {  3,   4, },
    [ ItemId::DEMONDRUG          ] = {  1,   7, },
    [ ItemId::MEGA_DEMONDRUG     ] = {  1,   8, },
    [ ItemId::ARMORSKIN          ] = {  1,   9, },
    [ ItemId::MEGA_ARMORSKIN     ] = {  1,  10, },
    [ ItemId::CATALYST           ] = {  4,  11, },
    [ ItemId::GUNPOWDER          ] = {  2,  15, },
    [ ItemId::LIFECRYSTALS       ] = {  1,  17, },
    [ ItemId::LIFEPOWDER         ] = {  1,  18, },
    [ ItemId::POWERCHARM         ] = {  1,  19, },
    [ ItemId::ARMORCHARM         ] = {  1,  20, },
    [ ItemId::TRANQUILIZER       ] = {  3,  21, },
    [ ItemId::RAW_MEAT           ] = {  3,  24, },
    [ ItemId::WELL_DONE_STEAK    ] = {  3,  27, },
    [ ItemId::BURNT_MEAT         ] = {  1,  30, },
    [ ItemId::BURNT_FISH         ] = {  1,  31, },
    [ ItemId::THROWING_KNIFE     ] = {  3,  32, },
    [ ItemId::BOMB_MATERIAL      ] = {  6,  35, },
    [ ItemId::SPIDERWEB          ] = {  1,  41, },
    [ ItemId::NET                ] = {  4,  42, },
    [ ItemId::TRAP_TOOL          ] = {  1,  46, },
    [ ItemId::SMALL_BARREL       ] = {  1,  47, },
    [ ItemId::SM_BARREL_BOMB     ] = {  2,  48, },
    [ ItemId::LG_BARREL_BOMB     ] = {  1,  50, },
    [ ItemId::BOUNCE_BOMB        ] = {  1,  51, },
    [ ItemId::HUSKBERRY          ] = { 20,  52, },
    [ ItemId::SM_BONE_HUSK       ] = {  8,  72, },
    [ ItemId::LG_BONE_HUSK       ] = {  3,  80, },
    [ ItemId::EMPTY_BOTTLE       ] = {  6,  83, },
    [ ItemId::CRICKET            ] = {  1,  89, },
    [ ItemId::WORM               ] = {  1,  90, },
    [ ItemId::FIREFLY            ] = {  2,  91, },
    [ ItemId::FROG               ] = {  1,  93, },
    [ ItemId::EXPAND_PICKAXE     ] = { 24,  94, },
    [ ItemId::WHETSTONE          ] = {  1, 118, },
    [ ItemId::GARBAGE            ] = {  1, 119, },
    [ ItemId::FLUTE              ] = {  1, 120, },
    [ ItemId::HONEY              ] = {  2, 121, },
    [ ItemId::HERB               ] = {  1, 123, },
    [ ItemId::ANTIDOTE_HERB      ] = {  3, 124, },
    [ ItemId::FIRE_HERB          ] = {  2, 127, },
    [ ItemId::IVY                ] = {  1, 129, },
    [ ItemId::SLEEP_HERB         ] = {  1, 130, },
    [ ItemId::SAP_PLANT          ] = {  4, 131, },
    [ ItemId::CACTUS_FLOWER      ] = {  2, 135, },
    [ ItemId::HOT_PEPPER         ] = {  2, 137, },
    [ ItemId::BLUE_MUSHROOM      ] = {  1, 139, },
    [ ItemId::DRAGON_SEED        ] = {  1, 140, },
    [ ItemId::NEEDLEBERRY        ] = {  2, 141, },
    [ ItemId::BOMBERRY           ] = {  1, 143, },
    [ ItemId::TROPICAL_BERRY     ] = {  1, 144, },
    [ ItemId::STONE              ] = {  1, 145, },
    [ ItemId::IRON_ORE           ] = {  1, 146, },
    [ ItemId::EARTH_CRYSTAL      ] = {  1, 147, },
    [ ItemId::MACHALITE_ORE      ] = {  2, 148, },
    [ ItemId::DRAGONITE_ORE      ] = {  1, 150, },
    [ ItemId::CARBALITE_ORE      ] = {  1, 151, },
    [ ItemId::ELTALITE_ORE       ] = {  1, 152, },
    [ ItemId::MELLANJE_ORE       ] = {  1, 153, },
    [ ItemId::PURECRYSTAL        ] = {  1, 154, },
    [ ItemId::ICE_CRYSTAL        ] = {  2, 155, },
    [ ItemId::ARMOR_STONE        ] = {  5, 157, },
    [ ItemId::BURST_ARROWANA     ] = {  1, 162, },
    [ ItemId::GODBUG             ] = {  1, 163, },
    [ ItemId::THUNDERBUG         ] = {  1, 164, },
    [ ItemId::BLNGO_BLZRD_BALL   ] = {  1, 165, },
    [ ItemId::INFERIOR_FLYN_CRN  ] = {  1, 166, },
    [ ItemId::HNDLELSS_GLD_BLD   ] = {  1, 167, },
    [ ItemId::BTTMLSS_OLD_VASE   ] = {  1, 168, },
    [ ItemId::HOLED_SHAKA_MASK   ] = {  1, 169, },
    [ ItemId::TORN_OLD_BOOK      ] = {  1, 170, },
    [ ItemId::TAILLESS_CAT_STATU ] = {  1, 171, },
};

typedef u16 MixMaterialItemIds[2];
MixMaterialItemIds MIX_MATERIAL_ITEM_IDS[173] = {
    { ItemId::HERB,               /* + */ ItemId::BLUE_MUSHROOM,      /* = ItemId::POTION */               },
    { ItemId::POTION,             /* + */ ItemId::HONEY,              /* = ItemId::MEGA_POTION */          },
    { ItemId::BLUE_MUSHROOM,      /* + */ ItemId::GODBUG,             /* = ItemId::NUTRIENTS */            },
    { ItemId::NUTRIENTS,          /* + */ ItemId::HONEY,              /* = ItemId::MEGA_NUTRIENTS */       },
    { ItemId::ANTIDOTE_HERB,      /* + */ ItemId::BLUE_MUSHROOM,      /* = ItemId::ANTIDOTE */             },
    { ItemId::CACTUS_FLOWER,      /* + */ ItemId::BITTERBUG,          /* = ItemId::HERBAL_MEDICINE */      },
    { ItemId::MEGA_NUTRIENTS,     /* + */ ItemId::DRAGON_TOADSTOOL,   /* = ItemId::MAX_POTION */           },
    { ItemId::IMMUNIZER,          /* + */ ItemId::KELBI_HORN,         /* = ItemId::ANCIENT_POTION */       },
    { ItemId::HONEY,              /* + */ ItemId::BITTERBUG,          /* = ItemId::CATALYST */             },
    { ItemId::CATALYST,           /* + */ ItemId::DRAGON_TOADSTOOL,   /* = ItemId::IMMUNIZER */            },
    { ItemId::CATALYST,           /* + */ ItemId::RARE_STEAK,         /* = ItemId::POWER_JUICE */          },
    { ItemId::WELL_DONE_STEAK,    /* + */ ItemId::POWER_EXTRACT,      /* = ItemId::MEGA_JUICE */           },
    { ItemId::HONEY,              /* + */ ItemId::SUNSET_HERB,        /* = ItemId::ENERGY_DRINK */         },
    { ItemId::CATALYST,           /* + */ ItemId::POWER_SEED,         /* = ItemId::DEMONDRUG */            },
    { ItemId::DEMONDRUG,          /* + */ ItemId::PALE_EXTRACT,       /* = ItemId::MEGA_DEMONDRUG */       },
    { ItemId::IMMUNIZER,          /* + */ ItemId::POWER_SEED,         /* = ItemId::POWER_PILL */           },
    { ItemId::CATALYST,           /* + */ ItemId::ARMOR_SEED,         /* = ItemId::ARMORSKIN */            },
    { ItemId::ARMORSKIN,          /* + */ ItemId::PALE_EXTRACT,       /* = ItemId::MEGA_ARMORSKIN */       },
    { ItemId::IMMUNIZER,          /* + */ ItemId::ARMOR_SEED,         /* = ItemId::ARMOR_PILL */           },
    { ItemId::HOT_PEPPER,         /* + */ ItemId::BITTERBUG,          /* = ItemId::HOT_DRINK */            },
    { ItemId::WELL_DONE_STEAK,    /* + */ ItemId::HOT_PEPPER,         /* = ItemId::HOT_MEAT */             },
    { ItemId::ICE_CRYSTAL,        /* + */ ItemId::BITTERBUG,          /* = ItemId::COOL_DRINK */           },
    { ItemId::WELL_DONE_STEAK,    /* + */ ItemId::ICE_CRYSTAL,        /* = ItemId::COLD_MEAT */            },
    { ItemId::HOT_PEPPER,         /* + */ ItemId::SPECIAL_MUSHROOM,   /* = ItemId::SPICY_MUSHROOM */       },
    { ItemId::TROPICAL_BERRY,     /* + */ ItemId::ICE_CRYSTAL,        /* = ItemId::FROZEN_BERRY */         },
    { ItemId::FIRE_HERB,          /* + */ ItemId::RUMBLEFISH,         /* = ItemId::THAWING_AGENT */        },
    { ItemId::RAW_MEAT,           /* + */ ItemId::TOADSTOOL,          /* = ItemId::POISONED_MEAT */        },
    { ItemId::RAW_MEAT,           /* + */ ItemId::PARASHROOM,         /* = ItemId::TAINTED_MEAT */         },
    { ItemId::RAW_MEAT,           /* + */ ItemId::SLEEP_HERB,         /* = ItemId::DRUGGED_MEAT */         },
    { ItemId::SAP_PLANT,          /* + */ ItemId::STONE,              /* = ItemId::BOMB_MATERIAL */        },
    { ItemId::BOMB_MATERIAL,      /* + */ ItemId::SUNSET_HERB,        /* = ItemId::DEODORANT */            },
    { ItemId::BOMB_MATERIAL,      /* + */ ItemId::IVY,                /* = ItemId::SMOKE_BOMB */           },
    { ItemId::BOMB_MATERIAL,      /* + */ ItemId::TOADSTOOL,          /* = ItemId::POISON_SMOKE_BMB */     },
    { ItemId::BOMB_MATERIAL,      /* + */ ItemId::FLASHBUG,           /* = ItemId::FLASH_BOMB */           },
    { ItemId::BOMB_MATERIAL,      /* + */ ItemId::DUNG,               /* = ItemId::DUNG_BOMB */            },
    { ItemId::SAP_PLANT,          /* + */ ItemId::PAINTBERRY,         /* = ItemId::PAINTBALL */            },
    { ItemId::BOMB_MATERIAL,      /* + */ ItemId::EXCITESHROOM,       /* = ItemId::FARCASTER */            },
    { ItemId::FIRE_HERB,          /* + */ ItemId::NITROSHROOM,        /* = ItemId::GUNPOWDER */            },
    { ItemId::SMALL_BARREL,       /* + */ ItemId::FIRE_HERB,          /* = ItemId::SM_BARREL_BOMB */       },
    { ItemId::SM_BARREL_BOMB,     /* + */ ItemId::BURST_ARROWANA,     /* = ItemId::SM_BARREL_BOMB_PLUS */  },
    { ItemId::GUNPOWDER,          /* + */ ItemId::LARGE_BARREL,       /* = ItemId::LG_BARREL_BOMB */       },
    { ItemId::LG_BARREL_BOMB,     /* + */ ItemId::SCATTERFISH,        /* = ItemId::LG_BARREL_BOMB_PLUS */  },
    { ItemId::BURST_ARROWANA,     /* + */ ItemId::THUNDERBUG,         /* = ItemId::LIGHTNING_ROD */        },
    { ItemId::SM_BARREL_BOMB,     /* + */ ItemId::VESPOID_WING,       /* = ItemId::BOUNCE_BOMB */          },
    { ItemId::BOUNCE_BOMB,        /* + */ ItemId::BOMB_ARROWANA,      /* = ItemId::BOUNCE_BOMB_PLUS */     },
    { ItemId::GUNPOWDER,          /* + */ ItemId::SCREAMER,           /* = ItemId::SONIC_BOMB */           },
    { ItemId::SPIDERWEB,          /* + */ ItemId::IVY,                /* = ItemId::NET */                  },
    { ItemId::NET,                /* + */ ItemId::TRAP_TOOL,          /* = ItemId::PITFALL_TRAP */         },
    { ItemId::TRAP_TOOL,          /* + */ ItemId::GENPREY_FANG,       /* = ItemId::SHOCK_TRAP */           },
    { ItemId::WORM,               /* + */ ItemId::YAMBUG,             /* = ItemId::TUNA_BAIT */            },
    { ItemId::CRICKET,            /* + */ ItemId::BUGHOPPER,          /* = ItemId::ARROWANA_BAIT */        },
    { ItemId::FIREFLY,            /* + */ ItemId::SNAKEBEE_LARVA,     /* = ItemId::GOLDENFISH_BAIT */      },
    { ItemId::STONE,              /* + */ ItemId::BONE,               /* = ItemId::OLD_PICKAXE */          },
    { ItemId::IRON_ORE,           /* + */ ItemId::BONE,               /* = ItemId::IRON_PICKAXE */         },
    { ItemId::MACHALITE_ORE,      /* + */ ItemId::BONE,               /* = ItemId::MEGA_PICKAXE */         },
    { ItemId::NET,                /* + */ ItemId::MYSTERY_BONE,       /* = ItemId::OLD_BUGNET */           },
    { ItemId::NET,                /* + */ ItemId::SM_MONSTER_BONE,    /* = ItemId::BUGNET */               },
    { ItemId::NET,                /* + */ ItemId::MED_MONSTER_BONE,   /* = ItemId::MEGA_BUGNET */          },
    { ItemId::EARTH_CRYSTAL,      /* + */ ItemId::BITTERBUG,          /* = ItemId::ANTISEPTIC_STONE */     },
    { ItemId::GODBUG,             /* + */ ItemId::WYVERN_FANG,        /* = ItemId::LIFECRYSTALS */         },
    { ItemId::LIFECRYSTALS,       /* + */ ItemId::WYVERN_CLAW,        /* = ItemId::LIFEPOWDER */           },
    { ItemId::LIFEPOWDER,         /* + */ ItemId::FLUTE,              /* = ItemId::HEALTH_FLUTE */         },
    { ItemId::FLUTE,              /* + */ ItemId::ANTISEPTIC_STONE,   /* = ItemId::ANTIDOTE_FLUTE */       },
    { ItemId::MEGA_DEMONDRUG,     /* + */ ItemId::MED_MONSTER_BONE,   /* = ItemId::DEMON_FLUTE */          },
    { ItemId::MEGA_ARMORSKIN,     /* + */ ItemId::MED_MONSTER_BONE,   /* = ItemId::ARMOR_FLUTE */          },
    { ItemId::THROWING_KNIFE,     /* + */ ItemId::TOADSTOOL,          /* = ItemId::POISON_THRW_KNF */      },
    { ItemId::THROWING_KNIFE,     /* + */ ItemId::SLEEP_HERB,         /* = ItemId::SLEEPING_THR_KNF */     },
    { ItemId::THROWING_KNIFE,     /* + */ ItemId::PARASHROOM,         /* = ItemId::PARALYZE_THR_KNF */     },
    { ItemId::WHETSTONE,          /* + */ ItemId::SM_MONSTER_BONE,    /* = ItemId::BOOMERANG */            },
    { ItemId::POWERCHARM,         /* + */ ItemId::LAO_SHANS_CLAW,     /* = ItemId::POWERTALON */           },
    { ItemId::ARMORCHARM,         /* + */ ItemId::LAO_SHANS_CLAW,     /* = ItemId::ARMORTALON */           },
    { ItemId::HUSKBERRY,          /* + */ ItemId::NEEDLEBERRY,        /* = ItemId::NORMAL_S_LV2 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::RUMBLEFISH,         /* = ItemId::NORMAL_S_LV3 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::VELOCIPREY_FANG,    /* = ItemId::PIERCE_S_LV1 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::PIN_TUNA,           /* = ItemId::PIERCE_S_LV2 */         },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::PIN_TUNA,           /* = ItemId::PIERCE_S_LV3 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::SCATTERNUT,         /* = ItemId::PELLET_S_LV1 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::WYVERN_FANG,        /* = ItemId::PELLET_S_LV2 */         },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::WYVERN_FANG,        /* = ItemId::PELLET_S_LV3 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::BURST_ARROWANA,     /* = ItemId::CRAG_S_LV1 */           },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::BURST_ARROWANA,     /* = ItemId::CRAG_S_LV2 */           },
    { ItemId::LG_BONE_HUSK,       /* + */ ItemId::BOMB_ARROWANA,      /* = ItemId::CRAG_S_LV3 */           },
    { ItemId::HUSKBERRY,          /* + */ ItemId::BOMBERRY,           /* = ItemId::CLUST_S_LV1 */          },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::WYVERN_CLAW,        /* = ItemId::CLUST_S_LV2 */          },
    { ItemId::LG_BONE_HUSK,       /* + */ ItemId::SCATTERFISH,        /* = ItemId::CLUST_S_LV3 */          },
    { ItemId::HUSKBERRY,          /* + */ ItemId::FIRE_HERB,          /* = ItemId::FLAMING_S */            },
    { ItemId::HUSKBERRY,          /* + */ ItemId::KNIFE_MACKEREL,     /* = ItemId::WATER_S */              },
    { ItemId::HUSKBERRY,          /* + */ ItemId::FLASHBUG,           /* = ItemId::THUNDER_S */            },
    { ItemId::HUSKBERRY,          /* + */ ItemId::ICE_CRYSTAL,        /* = ItemId::FREEZE_S */             },
    { ItemId::LG_BONE_HUSK,       /* + */ ItemId::DRAGON_SEED,        /* = ItemId::DRAGON_S */             },
    { ItemId::HUSKBERRY,          /* + */ ItemId::HERB,               /* = ItemId::RECOV_S_LV1 */          },
    { ItemId::POTION,             /* + */ ItemId::HUSKBERRY,          /* = ItemId::RECOV_S_LV2 */          },
    { ItemId::HUSKBERRY,          /* + */ ItemId::TOADSTOOL,          /* = ItemId::POISON_S_LV1 */         },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::IOPREY_FANG,        /* = ItemId::POISON_S_LV2 */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::PARASHROOM,         /* = ItemId::PARA_S_LV1 */           },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::GENPREY_FANG,       /* = ItemId::PARA_S_LV2 */           },
    { ItemId::HUSKBERRY,          /* + */ ItemId::SLEEP_HERB,         /* = ItemId::SLEEP_S_LV1 */          },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::SLEEPYFISH,         /* = ItemId::SLEEP_S_LV2 */          },
    { ItemId::HUSKBERRY,          /* + */ ItemId::PAINTBERRY,         /* = ItemId::PAINT_S */              },
    { ItemId::HUSKBERRY,          /* + */ ItemId::POWER_SEED,         /* = ItemId::DEMON_S */              },
    { ItemId::HUSKBERRY,          /* + */ ItemId::ARMOR_SEED,         /* = ItemId::ARMOR_S */              },
    { ItemId::SM_BONE_HUSK,       /* + */ ItemId::WHETSTONE,          /* = ItemId::EMPTY_BOTTLE */         },
    { ItemId::EMPTY_BOTTLE,       /* + */ ItemId::TOADSTOOL,          /* = ItemId::POISON_COATING */       },
    { ItemId::EMPTY_BOTTLE,       /* + */ ItemId::PARASHROOM,         /* = ItemId::PARALYSIS_COATING */    },
    { ItemId::EMPTY_BOTTLE,       /* + */ ItemId::SLEEP_HERB,         /* = ItemId::SLEEP_COATING */        },
    { ItemId::EMPTY_BOTTLE,       /* + */ ItemId::NITROSHROOM,        /* = ItemId::POWER_COATING */        },
    { ItemId::EMPTY_BOTTLE,       /* + */ ItemId::KNIFE_MACKEREL,     /* = ItemId::CLOSE_RNG_COATING */    },
    { ItemId::EMPTY_BOTTLE,       /* + */ ItemId::PAINTBERRY,         /* = ItemId::PAINT_COATING */        },
    { ItemId::SLEEP_HERB,         /* + */ ItemId::PARASHROOM,         /* = ItemId::TRANQUILIZER */         },
    { ItemId::TRANQUILIZER,       /* + */ ItemId::THROWING_KNIFE,     /* = ItemId::TRANQ_THRWNG_KNF */     },
    { ItemId::TRANQUILIZER,       /* + */ ItemId::BOMB_MATERIAL,      /* = ItemId::TRANQ_BOMB */           },
    { ItemId::TRANQUILIZER,       /* + */ ItemId::SM_BONE_HUSK,       /* = ItemId::TRANQ_S */              },
    { ItemId::MACHALITE_ORE,      /* + */ ItemId::ARMOR_STONE,        /* = ItemId::ARMOR_SPHERE */         },
    { ItemId::ARMOR_STONE,        /* + */ ItemId::KILLER_BEETLE,      /* = ItemId::ARMOR_SPHERE */         },
    { ItemId::DRAGONITE_ORE,      /* + */ ItemId::ARMOR_STONE,        /* = ItemId::ARMOR_SPHERE_PLUS */    },
    { ItemId::ARMOR_STONE,        /* + */ ItemId::HERCUDROME,         /* = ItemId::ARMOR_SPHERE_PLUS */    },
    { ItemId::CARBALITE_ORE,      /* + */ ItemId::ARMOR_STONE,        /* = ItemId::HRD_ARMOR_SPHERE */     },
    { ItemId::ARMOR_STONE,        /* + */ ItemId::KING_SCARAB,        /* = ItemId::HRD_ARMOR_SPHERE */     },
    { ItemId::PURECRYSTAL,        /* + */ ItemId::ARMOR_STONE,        /* = ItemId::HVY_ARMOR_SPHERE */     },
    { ItemId::ELTALITE_ORE,       /* + */ ItemId::ARMOR_STONE,        /* = ItemId::RYL_ARMOR_SPHERE */     },
    { ItemId::ARMOR_STONE,        /* + */ ItemId::EMPEROR_CRICKET,    /* = ItemId::RYL_ARMOR_SPHERE */     },
    { ItemId::MELLANJE_ORE,       /* + */ ItemId::ARMOR_STONE,        /* = ItemId::TRU_ARMOR_SPHERE */     },
    { ItemId::ARMOR_STONE,        /* + */ ItemId::PHANTOM_BUTTERFLY,  /* = ItemId::TRU_ARMOR_SPHERE */     },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::DISK_STONE,         /* = ItemId::DISK_STONE */           },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::IRON_ORE,           /* = ItemId::IRON_ORE */             },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::EARTH_CRYSTAL,      /* = ItemId::EARTH_CRYSTAL */        },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::MACHALITE_ORE,      /* = ItemId::MACHALITE_ORE */        },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::DRAGONITE_ORE,      /* = ItemId::DRAGONITE_ORE */        },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::CARBALITE_ORE,      /* = ItemId::CARBALITE_ORE */        },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::ELTALITE_ORE,       /* = ItemId::ELTALITE_ORE */         },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::UNION_ORE,          /* = ItemId::UNION_ORE */            },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::MELLANJE_ORE,       /* = ItemId::MELLANJE_ORE */         },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::FIRESTONE,          /* = ItemId::FIRESTONE */            },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::FIRECELL_STONE,     /* = ItemId::FIRECELL_STONE */       },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::LIGHTCRYSTAL,       /* = ItemId::LIGHTCRYSTAL */         },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::NOVACRYSTAL,        /* = ItemId::NOVACRYSTAL */          },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::PURECRYSTAL,        /* = ItemId::PURECRYSTAL */          },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::MONSTER_BONE_PLUS,  /* = ItemId::MONSTER_BONE_PLUS */    },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::HRD_MONSTER_BONE,   /* = ItemId::HRD_MONSTER_BONE */     },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::HVY_MONSTER_BONE,   /* = ItemId::HVY_MONSTER_BONE */     },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::CARPENTERBUG,       /* = ItemId::CARPENTERBUG */         },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::KILLER_BEETLE,      /* = ItemId::KILLER_BEETLE */        },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::HERCUDROME,         /* = ItemId::HERCUDROME */           },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::RARE_SCARAB,        /* = ItemId::RARE_SCARAB */          },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::KING_SCARAB,        /* = ItemId::KING_SCARAB */          },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::EMPEROR_CRICKET,    /* = ItemId::EMPEROR_CRICKET */      },
    { ItemId::EXPAND_PICKAXE,     /* + */ ItemId::PHANTOM_BUTTERFLY,  /* = ItemId::PHANTOM_BUTTERFLY */    },
    { ItemId::BLNGO_BLZRD_BALL,   /* + */ ItemId::BLNGO_FLRRY_BALL,   /* = ItemId::POKKE_SNOWMAN */        },
    { ItemId::INFERIOR_FLYN_CRN,  /* + */ ItemId::FLYN_CRWN_FRGMNT,   /* = ItemId::FELYNE_CROWN */         },
    { ItemId::HNDLELSS_GLD_BLD,   /* + */ ItemId::GLD_BLADELESS_HNDL, /* = ItemId::GLD_FLYN_JEWEL_SWD */   },
    { ItemId::BTTMLSS_OLD_VASE,   /* + */ ItemId::OLD_VASE_BOTTOM,    /* = ItemId::DYNASTY_VASE */         },
    { ItemId::HOLED_SHAKA_MASK,   /* + */ ItemId::SHAKALAKA_STONE,    /* = ItemId::MYSTERIOUS_MASK */      },
    { ItemId::TORN_OLD_BOOK,      /* + */ ItemId::OLD_BOOK_SCRAP,     /* = ItemId::ELDR_DRGN_RFRNC */      },
    { ItemId::TAILLESS_CAT_STATU, /* + */ ItemId::BROKEN_STONE_TAIL,  /* = ItemId::ANCNT_CAT_KING_STAT */  },
    { ItemId::FIREFLY,            /* + */ ItemId::SPECIAL_MUSHROOM,   /* = ItemId::HONEY */                },
    { ItemId::SAP_PLANT,          /* + */ ItemId::INSECT_HUSK,        /* = ItemId::HERB */                 },
    { ItemId::GARBAGE,            /* + */ ItemId::HOT_PEPPER,         /* = ItemId::FIRE_HERB */            },
    { ItemId::ANTIDOTE_HERB,      /* + */ ItemId::TOADSTOOL,          /* = ItemId::BLUE_MUSHROOM */        },
    { ItemId::BURNT_MEAT,         /* + */ ItemId::INSECT_HUSK,        /* = ItemId::RAW_MEAT */             },
    { ItemId::IVY,                /* + */ ItemId::MED_MONSTER_BONE,   /* = ItemId::LARGE_BARREL */         },
    { ItemId::SAP_PLANT,          /* + */ ItemId::SM_MONSTER_BONE,    /* = ItemId::SMALL_BARREL */         },
    { ItemId::HUSKBERRY,          /* + */ ItemId::IRON_ORE,           /* = ItemId::HUSKBERRY */            },
    { ItemId::NEEDLEBERRY,        /* + */ ItemId::EARTH_CRYSTAL,      /* = ItemId::NEEDLEBERRY */          },
    { ItemId::ANTIDOTE_HERB,      /* + */ ItemId::SLEEPYFISH,         /* = ItemId::SUSHIFISH */            },
    { ItemId::THUNDERBUG,         /* + */ ItemId::VELOCIPREY_HIDE,    /* = ItemId::RARE_STEAK */           },
    { ItemId::FROG,               /* + */ ItemId::FLUTE,              /* = ItemId::SCREAMER */             },
    { ItemId::ICE_CRYSTAL,        /* + */ ItemId::SLEEP_SAC,          /* = ItemId::MONSTER_FLUID */        },
    { ItemId::CACTUS_FLOWER,      /* + */ ItemId::THUNDERBUG,         /* = ItemId::PSYCHOSERUM */          },
    { ItemId::DRAGON_SEED,        /* + */ ItemId::PISCINE_LIVER,      /* = ItemId::POWER_EXTRACT */        },
    { ItemId::BOMBERRY,           /* + */ ItemId::VELOCIPREY_HIDE,    /* = ItemId::POWER_SEED */           },
    { ItemId::NEEDLEBERRY,        /* + */ ItemId::GIAPREY_HIDE,       /* = ItemId::ARMOR_SEED */           },
    { ItemId::BURNT_FISH,         /* + */ ItemId::SUNSET_HERB,        /* = ItemId::RARE_FISH */            },
    { ItemId::INVALID_ID,                 ItemId::INVALID_ID                                               },
};

MixQuantity MIX_QUANTITY_DEFINITIONS[7] = {
    { 1, { 100 } },
    { 1, { 70, 30 } },
    { 2, { 100 } },
    { 1, { 5, 85, 10 } },
    { 2, { 25, 50, 25 } },
    { 3, { 100 } },
    { 5, { 100 } },
};

MixQuantity *MIX_QUANTITIES[7] = {
    &MIX_QUANTITY_DEFINITIONS[0],
    &MIX_QUANTITY_DEFINITIONS[1],
    &MIX_QUANTITY_DEFINITIONS[2],
    &MIX_QUANTITY_DEFINITIONS[3],
    &MIX_QUANTITY_DEFINITIONS[4],
    &MIX_QUANTITY_DEFINITIONS[5],
    &MIX_QUANTITY_DEFINITIONS[6],
};

u8 MIX_MAX_QUANTITIES[7] = {
    1,
    2,
    2,
    3,
    4,
    3,
    5,
};

u8 MIX_RATES[7] = {
    100,
    95,
    90,
    85,
    75,
    65,
    55,
};

u16 COMBO_BOOK_IDS[5] = {
    ItemId::BOOK_OF_COMBOS_1,
    ItemId::BOOK_OF_COMBOS_2,
    ItemId::BOOK_OF_COMBOS_3,
    ItemId::BOOK_OF_COMBOS_4,
    ItemId::BOOK_OF_COMBOS_5,
};

u8 COMBO_BOOK_BONUSES[6] = {
    0, 5, 10, 20, 30, 50,
};
